// <auto-generated />
using Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230919072441_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<string>("ImdbURL")
                        .HasColumnType("longtext");

                    b.Property<int>("Released")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Genre = "Bogus.DataSets.Music,Bogus.DataSets.Music,Bogus.DataSets.Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "Bogus.DataSets.Address,Bogus.DataSets.Address,Bogus.DataSets.Address",
                            Released = 2022,
                            Synopsis = "Bogus.DataSets.Lorem",
                            Title = "Bogus.DataSets.Name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
