// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230920071249_InitialMigration1")]
    partial class InitialMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<string>("ImdbURL")
                        .HasColumnType("longtext");

                    b.Property<int>("Released")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Classical,Rap,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "79065 Bechtelar Walks, Hahnside, Albania,7242 Leannon Fort, South Rocky, Bermuda,3329 Jena Club, East Sabrina, Turks and Caicos Islands",
                            Released = 2023,
                            Synopsis = "Aperiam quos facere incidunt eligendi molestias velit. Adipisci magni iste veniam ut dolor ut aspernatur. Et ea odit enim tenetur ipsum est rem id aliquam. Nemo enim reprehenderit consequuntur voluptas repellendus voluptatem vero ea. Id sit ea.",
                            Title = "Melody"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Rock,Non Music,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "1549 Herzog Circle, South Priscilla, Brazil,202 Angeline Bridge, North Libbyfort, Dominica,3726 Elwyn Station, O'Connellhaven, Micronesia",
                            Released = 2023,
                            Synopsis = "Excepturi debitis neque voluptatum et rem fuga sunt aut. Error eligendi sunt sint. Est accusamus sunt corporis consequatur voluptas nam iste.",
                            Title = "Giovanna"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Folk,Metal,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "8494 Runolfsson Corners, Port Cristalborough, Venezuela,735 Leilani Mill, West Heather, Malawi,55772 Presley Greens, Ciceroberg, Switzerland",
                            Released = 2023,
                            Synopsis = "Rerum molestias omnis. Dicta quia voluptatem. Et ut iure quia et omnis modi ullam voluptas dolorem. Modi sapiente corrupti neque vitae. Dolores consequuntur unde delectus.",
                            Title = "Halie"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Rap,Soul,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "7944 Tillman Mount, Wolfmouth, Bosnia and Herzegovina,631 Rowe Valley, Port Velma, Lao People's Democratic Republic,02111 Berniece Inlet, West Dell, Bulgaria",
                            Released = 2023,
                            Synopsis = "Illum expedita cumque corporis inventore praesentium fugit et. Vel dolorem unde. Facilis ullam ea quo et et totam qui autem repellendus. Nihil voluptatem natus.",
                            Title = "Jordane"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Rap,Non Music,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "02952 Coty Knolls, Traceshire, Cyprus,465 Alfred Green, Donnyborough, Sweden,041 Wilderman Prairie, East Harmonyborough, Kiribati",
                            Released = 2022,
                            Synopsis = "Nihil repellat error fugit autem a nam debitis vel. Qui voluptatum vitae. Expedita est est.",
                            Title = "Maiya"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Rock,Stage And Screen,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "5582 Trent Coves, Zulauffort, Argentina,91799 Kameron Rue, Lake Claudine, Mauritania,57648 Kennith Green, Port Doviefort, Guatemala",
                            Released = 2023,
                            Synopsis = "Voluptatem animi optio laudantium. Ipsam voluptatem quas sed sunt cumque rerum officiis ducimus quidem. Quaerat voluptate libero quasi minima totam voluptatem natus. Libero modi sed sed cupiditate. Tenetur necessitatibus soluta illo eaque eum repudiandae est aut. Et voluptas modi rerum atque voluptas necessitatibus sapiente aut.",
                            Title = "Fidel"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Folk,Funk,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "612 Jones Village, Jensenberg, Saint Martin,9621 Weimann Villages, Lake Rosella, Estonia,82667 Lucius Courts, South Minerva, Dominican Republic",
                            Released = 2023,
                            Synopsis = "Ea eos qui. Natus vel ut natus exercitationem corrupti cumque quam saepe. Consectetur deserunt blanditiis et ut dolor et nostrum. Quos commodi autem velit aliquid dolores veritatis sunt ipsum est.",
                            Title = "Macie"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Non Music,Soul,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "397 Zboncak Vista, Farrellfort, Libyan Arab Jamahiriya,60274 Dooley Ridges, Rahulmouth, Argentina,7607 Hahn Viaduct, Turcottefurt, Libyan Arab Jamahiriya",
                            Released = 2023,
                            Synopsis = "Molestiae maxime veniam nostrum soluta ducimus nihil similique. Quis aut delectus fugit qui et. Expedita veniam nam quia neque sint voluptas enim dolorum officiis. Et ipsum sint laboriosam eos ut aperiam vel non excepturi. Sint similique accusamus sed. Harum voluptatum et.",
                            Title = "Serenity"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Rap,Latin,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "8689 Chloe Rapids, New Jaquan, Iceland,8738 Bernadine Glens, Port Marty, Malaysia,6400 Abshire Village, Conroyside, Nicaragua",
                            Released = 2023,
                            Synopsis = "Excepturi qui sit. At suscipit aspernatur aut excepturi porro ipsam error molestiae sunt. Est vel sunt vel eos ut occaecati sed.",
                            Title = "Kole"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Latin,Hip Hop,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "78280 Maude Radial, Bergstromton, Sweden,2253 Veum Vista, South Emilburgh, Djibouti,8345 Green Lake, Champlintown, Mexico",
                            Released = 2022,
                            Synopsis = "In rerum quas. Repudiandae delectus vero maxime autem omnis aliquid dicta. Quos rem eaque et iure asperiores quisquam commodi asperiores. Eos possimus sequi labore esse commodi ducimus ratione eos nostrum.",
                            Title = "Ryan"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Soul,Non Music,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "230 Roob Shore, Nikitaport, Syrian Arab Republic,7002 Steve Ports, New Luistown, Saint Vincent and the Grenadines,421 Hackett Isle, Port Sibylfort, Haiti",
                            Released = 2023,
                            Synopsis = "Ratione quo autem odit eveniet nostrum et et. Quo rerum fuga nihil qui quas harum magnam dolor. Dignissimos quisquam vel. Sapiente labore sed. Dolorum doloremque ut temporibus culpa. Saepe ea eum odit.",
                            Title = "Aniyah"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Rap,Latin,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "37785 Demond Passage, Kulasstad, Germany,33628 Bosco Extension, Deefort, Martinique,67329 Kutch Crest, Wardtown, Guatemala",
                            Released = 2022,
                            Synopsis = "Adipisci consequatur expedita quidem nihil placeat distinctio suscipit magni reprehenderit. Qui omnis rem quasi quia voluptatem nisi totam animi harum. Ut sed voluptas et quis laudantium. Quidem et incidunt distinctio voluptate. Officia saepe laboriosam temporibus doloremque.",
                            Title = "Otis"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Classical,Rock,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "87998 Derick Stravenue, Port Friedaview, Svalbard & Jan Mayen Islands,1209 Senger Tunnel, New Toreybury, Tokelau,339 Hills Radial, Watsicaville, Guatemala",
                            Released = 2023,
                            Synopsis = "A odit est omnis. Sed fuga nobis nam iusto quo id quod autem natus. Debitis vel amet nisi illum eos minus. Nostrum hic impedit inventore eos quod. Eveniet iste et. Eligendi occaecati saepe voluptates natus pariatur porro deleniti.",
                            Title = "Delphine"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Rap,Rap,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "640 Jody Drive, New Guillermo, Vietnam,634 Hermina Grove, East Kurtisland, Vanuatu,51731 Corene Walk, Port Ritastad, Heard Island and McDonald Islands",
                            Released = 2022,
                            Synopsis = "Qui et aut suscipit magnam nesciunt sit. Eius cumque officia rem rerum quaerat incidunt cupiditate. A id tenetur. Architecto sint voluptatem. Autem repudiandae labore ut voluptatem iusto beatae debitis ut voluptatem. Voluptatem deserunt quia ex earum dolorum architecto ea porro esse.",
                            Title = "Friedrich"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Funk,World,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "41500 Glover Tunnel, Cristland, Benin,3745 Kertzmann Ferry, East Orville, Bosnia and Herzegovina,334 Marques Knoll, Nicklausfort, New Caledonia",
                            Released = 2022,
                            Synopsis = "Adipisci veniam fuga perspiciatis. Numquam quam quisquam qui illum eos saepe aliquam voluptatum. Commodi dolor nemo est recusandae aspernatur vero quia. Qui expedita optio et et et. Et culpa rerum unde dolorem. Sit perferendis asperiores qui voluptate voluptate assumenda voluptatem architecto.",
                            Title = "Oleta"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Classical,Non Music,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "506 Brendon Cliffs, Hirammouth, Algeria,90165 Emery Villages, East Anahi, Belarus,03107 Felipa Cape, North Melyna, Burkina Faso",
                            Released = 2022,
                            Synopsis = "Et dolorum similique dolores omnis voluptas corporis. Et et similique consectetur debitis officia et sed dolorum eos. Et provident aut ut et voluptatibus quia. Cum aut assumenda ea quis consequatur et. Similique id minima velit quia et optio totam. Consequatur sed eos eligendi deleniti qui commodi ut.",
                            Title = "Junior"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Hip Hop,Blues,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "02324 Fredrick Plaza, Dellafort, Morocco,0341 Powlowski Squares, Lake Reinhold, Malaysia,62452 Schmidt Summit, Mitchellside, Cambodia",
                            Released = 2022,
                            Synopsis = "Laudantium non ut non corporis earum. Natus consequatur placeat temporibus illo voluptatem. Dolores sit reprehenderit sapiente cum illum architecto commodi. Praesentium recusandae non aspernatur eligendi omnis tempore. Officia quidem sunt sint optio distinctio.",
                            Title = "Domenico"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Country,Classical,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "936 Stiedemann Stravenue, West Rosamond, Yemen,4672 Kuvalis Glen, Lake Emmanuelle, Tanzania,456 Bogan Field, Boehmton, Andorra",
                            Released = 2023,
                            Synopsis = "Ad architecto reprehenderit nulla minus quasi corporis aliquid. Molestiae et beatae vel dolor ex quod qui possimus voluptatem. Inventore et nulla. Numquam provident molestias qui sit reprehenderit aspernatur. Autem quasi sed rem. Esse reiciendis quisquam quis esse voluptate.",
                            Title = "Missouri"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Latin,Rock,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "20882 Tommie Camp, Port Cory, French Polynesia,1989 Eliezer Road, West Pat, Mexico,32277 Dion Skyway, Amyachester, Bermuda",
                            Released = 2022,
                            Synopsis = "Nostrum sit eos officia blanditiis. Ad doloremque similique sint et reprehenderit ab dolores. Ullam officiis aut inventore sunt eos vel eos sit. Itaque ea praesentium quo consectetur et quidem molestias repellat repellendus. Laborum quae voluptates est perferendis voluptas quis dolorem maiores. Et quia dolore ut.",
                            Title = "Audra"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Latin,Rap,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "0560 Baby Route, New Ashlynn, Cayman Islands,7801 Ebert Rapid, Franciscastad, Panama,39980 Ed Lake, O'Konhaven, Nauru",
                            Released = 2023,
                            Synopsis = "Perferendis et quod in asperiores cumque architecto vel corporis. Minima corporis non fugiat. Atque iusto est. Atque et quisquam qui neque. Dolor totam voluptas sint sed laudantium. Est quis non deleniti incidunt unde.",
                            Title = "Mathilde"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "World,Pop,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "31841 Fabian Extension, East Sistermouth, Venezuela,6910 Yundt Fords, West Danika, Martinique,23434 Philip Flat, Miastad, Falkland Islands (Malvinas)",
                            Released = 2022,
                            Synopsis = "Accusantium quasi iusto consectetur qui voluptatibus ipsum tenetur blanditiis. Sapiente eos rerum dolores. Voluptates dolorem id illum tempora doloremque accusantium esse.",
                            Title = "Joey"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Metal,Stage And Screen,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "95709 Robyn Ramp, New Laron, Macedonia,69230 Heaven Points, West Weston, Israel,6233 Gislason Ramp, East Ayanaland, South Africa",
                            Released = 2023,
                            Synopsis = "Tenetur quaerat laboriosam praesentium qui libero aut enim adipisci. Adipisci quasi iste mollitia assumenda nam. Dicta quidem et.",
                            Title = "Gonzalo"
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Electronic,Hip Hop,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "996 Antwon Row, Kerluketown, Jordan,09731 Klocko Lake, Liamfort, Indonesia,80304 Schultz Course, Moorechester, Mali",
                            Released = 2022,
                            Synopsis = "Hic dolore id quas consequatur. Quas inventore rerum velit. Vel ipsa voluptatem molestiae alias quisquam incidunt adipisci.",
                            Title = "Diego"
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Pop,Latin,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "432 Eva Bridge, Lake Leta, Azerbaijan,436 Osborne Falls, Goldnerview, Cameroon,7485 Cedrick Creek, Shieldsland, Iceland",
                            Released = 2023,
                            Synopsis = "Non veritatis ducimus sunt veniam quasi et tenetur at distinctio. Enim deserunt quibusdam. Qui temporibus excepturi voluptatem consequatur architecto porro sunt necessitatibus.",
                            Title = "Myah"
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Country,Rap,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "85189 Katherine Crescent, Port Estrellafort, Seychelles,69697 Oran Trail, West Royalborough, Equatorial Guinea,827 Norval Mall, South Jaiden, Djibouti",
                            Released = 2022,
                            Synopsis = "Alias doloremque culpa sunt. Consequuntur quo omnis qui. Et asperiores odio ex est quia quidem. Sit qui eum autem.",
                            Title = "Carmelo"
                        },
                        new
                        {
                            Id = 26,
                            Genre = "Soul,Folk,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "26388 Bogan Glen, Adolfstad, Tunisia,076 Lenora Path, West Juniusmouth, Tanzania,710 Cronin Parkway, Port Dayana, United States of America",
                            Released = 2023,
                            Synopsis = "Omnis et maxime. Architecto est quam ad officia cupiditate est qui quia ex. Iusto eligendi unde modi fuga doloremque molestias est quod illum. Quisquam quo laborum quia tempora omnis minus beatae.",
                            Title = "Antonietta"
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Folk,Blues,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "9066 Stanton Neck, Tatyanamouth, Bouvet Island (Bouvetoya),52183 Brian Drive, New Olahaven, Norfolk Island,2469 Quitzon Spur, West Alvamouth, Zimbabwe",
                            Released = 2022,
                            Synopsis = "Corrupti ut doloribus perspiciatis debitis incidunt a est architecto odio. At recusandae quis saepe error dolor. Sunt explicabo cupiditate aut consectetur qui voluptatem laudantium. Deleniti dolorem aut quam dolores quisquam praesentium voluptatum officiis consectetur. Sed eos error sapiente assumenda. Rem cumque consectetur.",
                            Title = "Marjorie"
                        },
                        new
                        {
                            Id = 28,
                            Genre = "Reggae,Rap,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "1370 Hirthe Trail, Melanytown, Cote d'Ivoire,75618 Lubowitz Skyway, Justusport, Benin,105 Hermiston Lakes, North Georgianna, Burundi",
                            Released = 2022,
                            Synopsis = "Reiciendis doloremque quia aspernatur est unde quasi. Dolorum minima aliquid assumenda aperiam commodi dolore. Unde voluptate est sint non consectetur est perferendis sint.",
                            Title = "Clair"
                        },
                        new
                        {
                            Id = 29,
                            Genre = "World,Pop,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "68364 Waelchi Way, New Denisberg, Montserrat,9043 Elton Mountain, New Loraine, New Caledonia,64864 Corwin Stream, North Tony, Gabon",
                            Released = 2023,
                            Synopsis = "Corrupti rem similique suscipit fugit magni ratione necessitatibus aspernatur. Accusantium sit doloremque cum occaecati totam. Ipsam in magnam quas repellat veniam fugiat sit et. Sunt numquam quis necessitatibus unde et magnam.",
                            Title = "Kayleigh"
                        },
                        new
                        {
                            Id = 30,
                            Genre = "Rap,Country,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "52244 Altenwerth Glen, South Zellatown, Turkey,603 Emmitt Fields, North Adrian, Bahamas,132 Mueller Avenue, North Rollinfurt, Macao",
                            Released = 2022,
                            Synopsis = "Deleniti placeat autem ea et sint. Ad similique eius voluptatibus qui autem sint eos accusantium. Aut qui quibusdam quidem non sit at ut. Architecto impedit quia sint voluptatem neque. Et corporis omnis cupiditate sed.",
                            Title = "Lester"
                        },
                        new
                        {
                            Id = 31,
                            Genre = "Soul,Pop,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "0251 Williamson Courts, Wilfredomouth, South Africa,04895 Isaac Orchard, West Glendaport, Cape Verde,7377 Euna Green, Zackeryland, Costa Rica",
                            Released = 2023,
                            Synopsis = "Nulla eligendi voluptates non quibusdam. Sunt voluptas expedita. Modi sit laudantium. Ipsum qui molestiae impedit aut et.",
                            Title = "Devyn"
                        },
                        new
                        {
                            Id = 32,
                            Genre = "Pop,Folk,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "1945 Hettinger Underpass, Britneyburgh, American Samoa,10927 Murray Motorway, Treyborough, Angola,392 Spencer Pines, Erichberg, Mayotte",
                            Released = 2022,
                            Synopsis = "Aut velit perferendis. Voluptatem nemo et sapiente. Distinctio necessitatibus autem. Magnam nisi aut. Atque occaecati et deleniti expedita in. Nesciunt exercitationem qui neque et unde tenetur voluptatum veniam tenetur.",
                            Title = "Chelsea"
                        },
                        new
                        {
                            Id = 33,
                            Genre = "Stage And Screen,Latin,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "03096 Corwin Grove, Creminfort, Democratic People's Republic of Korea,903 Keanu Terrace, Port Bell, Estonia,563 Liana Ridges, Vicentabury, France",
                            Released = 2023,
                            Synopsis = "Aut commodi voluptas nulla. Qui ut repudiandae labore aut ab in in. Deleniti ad pariatur sit sint magnam nesciunt et eius. Quos voluptatum nulla aut quia eveniet quae qui sed autem. Accusamus possimus vero est dolorum eaque voluptate commodi non maiores.",
                            Title = "Samson"
                        },
                        new
                        {
                            Id = 34,
                            Genre = "Rap,Non Music,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "26099 Adriana Cape, South Lorna, Andorra,0813 Hahn Court, Port Ryleigh, Gambia,308 Connelly Highway, Browntown, Algeria",
                            Released = 2023,
                            Synopsis = "Cumque exercitationem odio consequatur in. Officiis quas voluptas facere itaque assumenda voluptatum inventore dolorem. Explicabo sed sunt perferendis ullam est porro fugit nobis.",
                            Title = "Mitchel"
                        },
                        new
                        {
                            Id = 35,
                            Genre = "Blues,Country,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "32305 Maxime View, Lake Gisselle, Slovenia,6045 Keshawn Ferry, Port Uriahfort, Antigua and Barbuda,24794 Gorczany Mission, North Lydia, France",
                            Released = 2023,
                            Synopsis = "Illum quaerat pariatur eius aperiam architecto voluptatem qui. Eum cumque explicabo deserunt. Molestias rem nesciunt fuga illo ut. Ipsam omnis corrupti voluptatibus. Iure aut facilis dolorem ad aut.",
                            Title = "Amaya"
                        },
                        new
                        {
                            Id = 36,
                            Genre = "Electronic,Country,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "3770 Cartwright Gateway, Port Erikashire, Faroe Islands,52539 Geo Drive, Port Leslieville, Saint Kitts and Nevis,73686 Price Fork, North Trishaville, Tanzania",
                            Released = 2022,
                            Synopsis = "At unde non enim odio est sunt est voluptate dolorum. Quia aut et incidunt architecto eligendi molestiae voluptatem. Ratione possimus sapiente id delectus quidem sed.",
                            Title = "Kieran"
                        },
                        new
                        {
                            Id = 37,
                            Genre = "Latin,Pop,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "8319 Klein Ridges, Port Audreanneton, Myanmar,7830 Marjorie Trace, Port Verniehaven, Turkey,560 Kariane Place, Dooleyport, South Georgia and the South Sandwich Islands",
                            Released = 2023,
                            Synopsis = "Ut asperiores iste corrupti laudantium vel tempora. Est voluptatum consequatur consectetur perferendis aut. Quidem repellat et voluptatibus et.",
                            Title = "Maeve"
                        },
                        new
                        {
                            Id = 38,
                            Genre = "Electronic,World,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "96223 Jude Inlet, Port Rhea, Uruguay,17200 Ebert Station, Darrionfurt, Zimbabwe,88856 Rico Pine, Port Donnellmouth, United States Minor Outlying Islands",
                            Released = 2022,
                            Synopsis = "Rerum aut vel quae omnis aperiam quis. Qui ullam ut eaque laborum non. Qui rerum aut quod distinctio et.",
                            Title = "Delmer"
                        },
                        new
                        {
                            Id = 39,
                            Genre = "Pop,Jazz,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "61339 Wiegand Circle, West Aliaport, Cyprus,8270 Elsa Plaza, North Chandlerstad, French Guiana,45885 Koch Falls, Gillianport, Azerbaijan",
                            Released = 2022,
                            Synopsis = "Quo quam nihil molestiae sit et aut harum sit voluptate. Omnis aut cum est optio. Impedit cumque sint nesciunt reprehenderit eum totam magni tempore.",
                            Title = "Ransom"
                        },
                        new
                        {
                            Id = 40,
                            Genre = "Stage And Screen,Latin,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "8021 Lexi Center, North Frankie, Sri Lanka,61520 McClure Burg, East Clevetown, Madagascar,04142 McCullough Shores, North Elinorport, Palau",
                            Released = 2022,
                            Synopsis = "Commodi fugiat ad temporibus amet debitis dicta quis aut quos. Sed adipisci corrupti dolorem et velit quisquam. Magni dolores totam enim sint nostrum voluptas dolor.",
                            Title = "Sallie"
                        },
                        new
                        {
                            Id = 41,
                            Genre = "Reggae,Metal,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "78936 Harvey Well, Hectorfort, Nepal,5775 Wiegand Drives, Lilyanfort, Guinea-Bissau,2501 Jena Expressway, Port Norris, Indonesia",
                            Released = 2023,
                            Synopsis = "Quos aut enim soluta. Placeat aut aut non doloremque. Sit animi numquam facere deserunt modi. Aut numquam maxime. Facere dolores aut.",
                            Title = "Omer"
                        },
                        new
                        {
                            Id = 42,
                            Genre = "Latin,Classical,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "110 Armstrong Knoll, Port Mylene, Cuba,031 Cecile Hollow, Port Kathleenmouth, Angola,648 Thompson Lakes, North Richieview, Spain",
                            Released = 2023,
                            Synopsis = "Corporis doloribus doloremque reiciendis aliquid ea consequatur velit facere est. Sint ea consequuntur odio neque sunt distinctio itaque maxime. Possimus et nihil voluptatem corporis laborum voluptas eveniet.",
                            Title = "Jerod"
                        },
                        new
                        {
                            Id = 43,
                            Genre = "Pop,Soul,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "594 Johnson Dale, North Ashlynnburgh, Australia,97263 Madie Grove, Wisokyport, Georgia,6671 Zemlak Shore, D'Amoremouth, South Africa",
                            Released = 2022,
                            Synopsis = "Nisi modi consequatur laboriosam. Natus omnis sequi rem hic aliquam molestiae. Sint odio neque quo. Repellat et praesentium. Fuga sunt perferendis.",
                            Title = "Forest"
                        },
                        new
                        {
                            Id = 44,
                            Genre = "Electronic,Folk,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "3152 Abshire Fords, South Alyssonland, Montenegro,62968 Kovacek Parkways, Port Nelle, Peru,8246 Kreiger Mountain, South Alecton, Jamaica",
                            Released = 2023,
                            Synopsis = "Commodi recusandae quaerat sed laboriosam consequatur voluptates nostrum eos. Sapiente quas et assumenda id. Exercitationem et omnis quasi corrupti et sint. Aut tenetur excepturi tempore cumque reiciendis ut sit quia et. Qui esse ut cum qui vel.",
                            Title = "Mathew"
                        },
                        new
                        {
                            Id = 45,
                            Genre = "Soul,World,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "394 Beer Landing, East Fredrick, Samoa,236 Lura Shore, McCulloughland, United States of America,054 Fadel Springs, Beerfurt, United States Minor Outlying Islands",
                            Released = 2022,
                            Synopsis = "Qui et fuga. Ex illum aperiam aut fugiat ipsam temporibus. Repudiandae ipsum sequi accusamus qui sequi harum explicabo molestias officia. Cumque modi commodi nesciunt rerum sunt quo suscipit iste. Laudantium accusantium occaecati iure neque eius.",
                            Title = "Carlotta"
                        },
                        new
                        {
                            Id = 46,
                            Genre = "Country,Jazz,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "866 Schiller Roads, Marvintown, Timor-Leste,2882 Homenick Plains, Lake Rylan, Micronesia,454 Berge Harbors, Ziemannmouth, Greece",
                            Released = 2022,
                            Synopsis = "Excepturi sequi corrupti. Sapiente nihil aut possimus quis soluta in. Atque qui minus ad illo autem nisi nobis vitae voluptas. Ut ea rerum at adipisci.",
                            Title = "Jackie"
                        },
                        new
                        {
                            Id = 47,
                            Genre = "Rap,Latin,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "3220 Kassulke Dale, East Osborne, Heard Island and McDonald Islands,360 Daugherty Fall, Jennyferborough, Wallis and Futuna,4918 Champlin Ferry, New Chloe, Falkland Islands (Malvinas)",
                            Released = 2023,
                            Synopsis = "Iste ea aut occaecati quo totam. Dolorem a similique. Architecto pariatur alias omnis nesciunt in distinctio quibusdam est facere. Eos quae dicta quia voluptates et. Est consequatur magnam earum itaque quia corporis officiis.",
                            Title = "Gabrielle"
                        },
                        new
                        {
                            Id = 48,
                            Genre = "Folk,Reggae,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "81856 Walker Forks, Ransomchester, Tonga,03463 Friesen Falls, West Brockborough, Virgin Islands, U.S.,6056 Arnulfo Station, Leuschkefort, Liberia",
                            Released = 2022,
                            Synopsis = "Doloribus recusandae mollitia consequatur eveniet harum. Aut sunt a nihil. Quis sint enim velit repellat repellat magnam mollitia et minima. Autem molestiae quisquam laboriosam asperiores ducimus natus fugiat.",
                            Title = "Clemmie"
                        },
                        new
                        {
                            Id = 49,
                            Genre = "Blues,Reggae,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "22437 Lauretta Alley, Ankundingstad, Niger,12322 Bobbie Parkway, Baumbachmouth, Svalbard & Jan Mayen Islands,77711 Millie Plains, Glennieland, Palestinian Territory",
                            Released = 2023,
                            Synopsis = "Quam dolore a nobis labore doloribus. Ut quo incidunt ad. Aliquam non et consequatur nesciunt rerum fuga. Consequatur ut qui nihil nesciunt beatae consectetur et.",
                            Title = "Jose"
                        },
                        new
                        {
                            Id = 50,
                            Genre = "Electronic,Country,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "770 Cartwright Path, North Gino, United Kingdom,951 Myriam Springs, Parkertown, Reunion,143 Tremblay Forge, Corwinmouth, Hong Kong",
                            Released = 2023,
                            Synopsis = "Reprehenderit saepe tenetur neque velit voluptatem cum nisi et quos. Atque assumenda quia ab voluptatem. Quaerat numquam illum dolor. Voluptate sed quidem maxime.",
                            Title = "Loraine"
                        },
                        new
                        {
                            Id = 51,
                            Genre = "Soul,Metal,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "453 Bechtelar Roads, Darrionview, Syrian Arab Republic,070 Moen Spur, Huelberg, France,881 Anabel Cliffs, Nikolasport, India",
                            Released = 2023,
                            Synopsis = "Ipsum iusto dolor porro occaecati consectetur dolor. Molestias et officia exercitationem dicta delectus aut ut molestiae occaecati. Veniam sed illum qui omnis officiis dolorum. Quia maxime libero officiis sint reiciendis. Voluptatem non et quaerat delectus blanditiis voluptate. Qui impedit ea.",
                            Title = "Alexzander"
                        },
                        new
                        {
                            Id = 52,
                            Genre = "Country,Soul,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "9792 Grayce Turnpike, Bergehaven, Portugal,6428 Alejandra Inlet, Hesselmouth, Saint Lucia,93281 Vicky Ports, Lake Chanceton, Finland",
                            Released = 2022,
                            Synopsis = "Maxime temporibus deserunt a voluptatem dolores eius aut rem et. Qui repudiandae qui quia quia non cupiditate dolor suscipit. Fuga et voluptatem libero ea rerum asperiores dicta. Asperiores nesciunt est autem magnam nesciunt.",
                            Title = "Hildegard"
                        },
                        new
                        {
                            Id = 53,
                            Genre = "World,World,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "95442 Huel Isle, Port Jaysonchester, Croatia,24037 Stroman Bypass, Joebury, Namibia,9022 Romaine Key, Ariannaview, Norfolk Island",
                            Released = 2023,
                            Synopsis = "Cupiditate praesentium alias odit tenetur quas. Aut quos et odit aut rem veritatis quaerat quis. Non deleniti dolorum.",
                            Title = "Jaida"
                        },
                        new
                        {
                            Id = 54,
                            Genre = "Metal,Metal,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "2296 Baumbach Haven, Stephanieshire, United States of America,10173 Nader Garden, Kevintown, Republic of Korea,68491 Bernardo Highway, North Lindsay, Saint Helena",
                            Released = 2023,
                            Synopsis = "Sed eius quia qui eos qui est quia dolores. Rerum non earum dolores. Nihil ipsa quae maxime. Et in quod.",
                            Title = "Erling"
                        },
                        new
                        {
                            Id = 55,
                            Genre = "Blues,Classical,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "170 Nichole Station, West Sunny, Japan,302 Ila Hollow, McClureville, Germany,98811 Satterfield Fort, Teaganfort, Niger",
                            Released = 2022,
                            Synopsis = "Sed pariatur repudiandae repellendus sequi sed. Aut labore eius vel laudantium et itaque. Voluptate fugit hic explicabo.",
                            Title = "Eldridge"
                        },
                        new
                        {
                            Id = 56,
                            Genre = "Funk,Country,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "5010 Carole Mountains, Corenefurt, Australia,300 Strosin Courts, South Juddfort, Mauritania,2526 Rosario Drive, New Annamariehaven, Kuwait",
                            Released = 2023,
                            Synopsis = "Sed velit maxime dignissimos et dicta qui deserunt officiis. Aliquam corrupti quo harum placeat eum. Sunt sit iusto ipsum.",
                            Title = "Christelle"
                        },
                        new
                        {
                            Id = 57,
                            Genre = "Rock,Stage And Screen,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "2779 Vincenzo Vista, West Alvena, Mexico,13941 Hirthe Island, Keeganton, Malaysia,203 Leif Squares, Mertzchester, Syrian Arab Republic",
                            Released = 2022,
                            Synopsis = "Rerum illo libero. Debitis ea placeat nesciunt quam. Est sit in praesentium.",
                            Title = "Vern"
                        },
                        new
                        {
                            Id = 58,
                            Genre = "Stage And Screen,Stage And Screen,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "25922 Shields Branch, South Adelineshire, Aruba,727 DuBuque Mews, Raphaelleborough, Luxembourg,833 Julius Harbor, South Sigurdmouth, Puerto Rico",
                            Released = 2023,
                            Synopsis = "Molestias enim sunt et accusamus voluptatem in magni. At odio hic autem non ad. Totam delectus et. Eos qui quidem nihil rerum a tenetur. Aut ut laboriosam.",
                            Title = "Magdalen"
                        },
                        new
                        {
                            Id = 59,
                            Genre = "Pop,Blues,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "8486 Gunner Bypass, Lake Shanelle, Monaco,676 Delpha Highway, Terrybury, Kiribati,403 Demetrius Forge, Cruickshankburgh, Qatar",
                            Released = 2023,
                            Synopsis = "Delectus fugiat architecto autem. Magni ullam ratione eum aperiam quod voluptate facere praesentium illo. Similique sit porro ea rerum adipisci nesciunt quo. Ut exercitationem et repellat nisi itaque atque aliquam. Sit aliquid placeat ipsum veritatis rerum expedita maxime.",
                            Title = "Barney"
                        },
                        new
                        {
                            Id = 60,
                            Genre = "Metal,Blues,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "68903 Tressa Summit, Leannonview, Tonga,9920 Jayden Cliffs, West Beau, Turks and Caicos Islands,283 Camylle Trace, New Pearlfort, Armenia",
                            Released = 2023,
                            Synopsis = "Quaerat ut fugiat eveniet dolores excepturi commodi. Et laudantium tempore sit maiores quia est. Eum ut nostrum quod illum blanditiis est alias eos. Officiis aut explicabo natus vel vel. Libero aut et rerum. Voluptatem consequatur qui vel ducimus.",
                            Title = "Carlo"
                        },
                        new
                        {
                            Id = 61,
                            Genre = "Non Music,Rock,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "6716 Paucek Branch, Sophieview, Tanzania,25576 Ondricka Parks, North Kadenfurt, Antigua and Barbuda,196 Considine Port, North Tyshawnmouth, Nicaragua",
                            Released = 2023,
                            Synopsis = "Ipsa dolorum quo molestiae esse unde minima fugiat rerum. Debitis saepe quaerat non. Aperiam et similique nihil nisi omnis. Minus harum consequatur eum et consequatur. Dolor nesciunt quaerat adipisci.",
                            Title = "Brandy"
                        },
                        new
                        {
                            Id = 62,
                            Genre = "Non Music,Latin,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "8535 Balistreri Mews, South Eviemouth, Netherlands,54789 Rowan Bypass, Lawsonfurt, Montserrat,7173 Russell Spur, North Odellview, Lesotho",
                            Released = 2023,
                            Synopsis = "Et quas eaque dolores quas possimus placeat. Sit ab consequatur. Doloremque perspiciatis natus doloribus aut ea aut.",
                            Title = "Margarette"
                        },
                        new
                        {
                            Id = 63,
                            Genre = "Blues,Country,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "77282 Coy Islands, Breanaberg, Tajikistan,1808 Alene Junction, Erdmanbury, Turks and Caicos Islands,20225 Friesen Walks, Roweton, Anguilla",
                            Released = 2023,
                            Synopsis = "Rerum distinctio dolorum assumenda vero consequuntur qui. Tenetur illum voluptates. Odio eum et. Aliquam qui repellendus occaecati doloremque ea qui.",
                            Title = "Margarett"
                        },
                        new
                        {
                            Id = 64,
                            Genre = "Soul,Non Music,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "6404 Volkman Underpass, North Jeffreyland, Australia,6460 Lesch Circles, Ferntown, Bulgaria,97855 Stracke Lights, Port Erichland, Uruguay",
                            Released = 2023,
                            Synopsis = "Quo cum libero. Quaerat qui nostrum ut quia non molestiae dolor incidunt modi. Magnam aspernatur nisi dolores sunt fuga reprehenderit.",
                            Title = "Alanna"
                        },
                        new
                        {
                            Id = 65,
                            Genre = "Country,Pop,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "7802 Eliane Freeway, Wolfmouth, Australia,417 Carroll Mountain, Retafurt, Bermuda,2324 Sporer Knolls, Baumbachburgh, Dominican Republic",
                            Released = 2023,
                            Synopsis = "Accusantium qui amet asperiores aperiam. Voluptas vel occaecati omnis deserunt dolor neque natus amet qui. Quo nesciunt architecto consequatur velit veniam hic. Libero nemo quisquam praesentium velit et neque tenetur.",
                            Title = "Winfield"
                        },
                        new
                        {
                            Id = 66,
                            Genre = "Blues,Soul,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "4540 Schmidt Crossing, East Garrick, Poland,525 Nathen Forge, Ottismouth, Niue,8658 Treutel Center, Harrisbury, Dominica",
                            Released = 2023,
                            Synopsis = "Reiciendis iusto odit voluptas laudantium. Nemo nam autem eveniet ut enim voluptas. Esse sint at harum. Debitis enim optio excepturi quis omnis repellat atque blanditiis mollitia.",
                            Title = "Alexandrea"
                        },
                        new
                        {
                            Id = 67,
                            Genre = "Rock,Latin,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "9590 Zieme Prairie, Alecland, Ecuador,206 Kristin Plains, West Dario, Eritrea,775 Zack Crescent, Feesttown, Tanzania",
                            Released = 2023,
                            Synopsis = "Repudiandae ea molestiae quam ipsa consequuntur aut. Porro quis ut optio ea quos explicabo expedita occaecati ut. Officia officiis ducimus nihil et unde facilis aperiam aspernatur at.",
                            Title = "Marielle"
                        },
                        new
                        {
                            Id = 68,
                            Genre = "Jazz,Funk,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "69396 Gleichner Parkway, South Ulises, Nigeria,9208 Farrell Knoll, Padbergport, New Caledonia,7871 Emard Junctions, Luettgenchester, United States of America",
                            Released = 2023,
                            Synopsis = "Provident sunt labore ipsum incidunt vel. Repellendus est consequatur. Ad a eveniet ut blanditiis laboriosam sunt nesciunt. Voluptate quis expedita explicabo animi qui.",
                            Title = "Melyna"
                        },
                        new
                        {
                            Id = 69,
                            Genre = "World,Soul,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "00609 Aglae Streets, Jedborough, Hong Kong,71987 Weldon Garden, Port Herminio, Saudi Arabia,22507 Archibald Plains, Daviston, Nicaragua",
                            Released = 2023,
                            Synopsis = "Velit sint odio fuga voluptatum et consequatur nihil quod quae. Accusantium ipsam nihil molestiae. Doloremque iste omnis dolorum exercitationem molestiae rerum asperiores laboriosam. Consequatur nam praesentium commodi aliquid voluptas tempore repudiandae et odio.",
                            Title = "Willie"
                        },
                        new
                        {
                            Id = 70,
                            Genre = "Rap,Country,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "142 Trevor Flats, Breitenbergburgh, Montserrat,88200 Baumbach Avenue, East Jaydefort, Norfolk Island,8692 Baumbach Mountain, Doylechester, Antigua and Barbuda",
                            Released = 2023,
                            Synopsis = "Eligendi est maiores quaerat modi animi. Sed et et. Non numquam ut repellendus tenetur praesentium nemo. Dolorum delectus qui nam in omnis necessitatibus placeat blanditiis illum. Ut omnis est. Officiis ullam aut aliquam magnam modi.",
                            Title = "Adrien"
                        },
                        new
                        {
                            Id = 71,
                            Genre = "Jazz,Rap,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "7352 Grimes Road, North Greenview, Austria,05657 Brendan Cliffs, North Alysonbury, Paraguay,6424 Koss Lane, Schneiderport, Congo",
                            Released = 2022,
                            Synopsis = "Sed nostrum in est delectus ab illum molestias recusandae et. Quis cumque corporis porro rem doloribus velit accusantium praesentium eius. Odit voluptatem ut quibusdam optio fugit consequatur asperiores atque sed.",
                            Title = "Faye"
                        },
                        new
                        {
                            Id = 72,
                            Genre = "Blues,Electronic,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "162 Kathryne Place, Goldnerfort, Trinidad and Tobago,32050 Alessandra Neck, Christopville, Portugal,52123 Volkman Junction, Lake Trycia, Cape Verde",
                            Released = 2023,
                            Synopsis = "Molestiae mollitia ipsum molestiae facilis sunt natus neque consequatur possimus. Et harum aliquam earum quidem fugit aut commodi distinctio. Ea repudiandae error possimus mollitia itaque placeat magni. Eaque dignissimos quia ea natus. Excepturi voluptatem quos beatae at ipsam ex.",
                            Title = "Gerard"
                        },
                        new
                        {
                            Id = 73,
                            Genre = "Reggae,Country,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "547 Volkman Camp, West Giovannafurt, San Marino,836 Jadon Fall, Fisherhaven, Argentina,2872 Avis Parkways, North Tony, Uzbekistan",
                            Released = 2023,
                            Synopsis = "Deleniti officiis distinctio aut animi quos iure. Et praesentium voluptate rerum nihil dolorem rem. Maiores dolores velit perferendis facilis. Sed consequuntur ipsum odit qui. Eligendi rerum non voluptatem ea cumque quo ut.",
                            Title = "Henri"
                        },
                        new
                        {
                            Id = 74,
                            Genre = "Classical,Folk,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "617 Zachary Circles, Sydneystad, Montenegro,921 Kenya Villages, Lydialand, United States Minor Outlying Islands,732 Fadel Cliff, Stromanchester, United Kingdom",
                            Released = 2023,
                            Synopsis = "Nihil et quo quia et corporis esse. Aspernatur esse a dignissimos et. Sint ea molestiae quia rerum nemo harum distinctio quis adipisci. Adipisci consequatur quidem nihil. Laudantium omnis neque laudantium sint.",
                            Title = "Fletcher"
                        },
                        new
                        {
                            Id = 75,
                            Genre = "Jazz,Electronic,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "664 Mills Hollow, East Rigobertochester, Guinea-Bissau,826 Alanis Mountain, Ramirostad, South Africa,78174 Bosco Course, Brekketon, Kuwait",
                            Released = 2023,
                            Synopsis = "Quam et exercitationem voluptates in aut non. Voluptatibus sequi ea sed veniam voluptatem quod sed. Ipsa quidem perferendis aut voluptate qui voluptate.",
                            Title = "Mark"
                        },
                        new
                        {
                            Id = 76,
                            Genre = "Metal,Folk,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "248 Ebert Pine, Hirthefort, Tunisia,15052 Arnoldo Plains, Padbergfort, Virgin Islands, U.S.,880 Maymie Tunnel, East Emmettview, Congo",
                            Released = 2023,
                            Synopsis = "Nemo aliquam sed quis vel. Nisi perspiciatis sed et neque quasi rerum rerum fuga aspernatur. Repellat est omnis impedit velit doloribus omnis voluptatum et.",
                            Title = "Ona"
                        },
                        new
                        {
                            Id = 77,
                            Genre = "Stage And Screen,Reggae,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "8552 Lucas Street, Gregoriachester, Poland,544 Sheila Trail, West Julianastad, Togo,759 Crist Extensions, New Sheila, Solomon Islands",
                            Released = 2023,
                            Synopsis = "Odit omnis aspernatur non rem minus. Non esse dolor nam doloribus. Qui cumque cupiditate corporis quo dolor asperiores id dolores.",
                            Title = "Andreanne"
                        },
                        new
                        {
                            Id = 78,
                            Genre = "Jazz,Reggae,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "872 Feest View, Ullrichport, Belgium,51501 Marvin Landing, Predovicburgh, Uruguay,18783 Damaris Spurs, West Larry, Monaco",
                            Released = 2022,
                            Synopsis = "Eos neque quas repellat et. Vel ratione nesciunt in voluptatibus officia voluptates dolores deleniti. Consequuntur corrupti ex nam consequatur.",
                            Title = "Sydnie"
                        },
                        new
                        {
                            Id = 79,
                            Genre = "Electronic,Non Music,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "301 Fahey Garden, North Presley, French Guiana,035 Boris Loaf, Wilmerside, Hong Kong,83311 Olen Mews, West Bill, Austria",
                            Released = 2023,
                            Synopsis = "Quos commodi est. Alias consectetur corrupti tenetur et dolorem. Consequatur aperiam vel est esse voluptas ut. Natus omnis laborum. Eos ut molestiae in a accusantium et.",
                            Title = "Elisa"
                        },
                        new
                        {
                            Id = 80,
                            Genre = "Latin,Rap,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "156 Kayla Spurs, West Alexzandermouth, Sudan,34769 Little Ways, West Margrettown, Martinique,33575 Yost Mission, Luigiburgh, Kenya",
                            Released = 2023,
                            Synopsis = "Reprehenderit ipsum nemo voluptas aut corrupti. Quo ipsa eum voluptatibus mollitia provident amet. In iste et enim vel maxime odit voluptatem. Ea suscipit laudantium eveniet vel. Provident provident commodi porro non. Aliquam laborum et dolor architecto animi voluptatem sit dolores tempore.",
                            Title = "Lew"
                        },
                        new
                        {
                            Id = 81,
                            Genre = "World,Pop,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "119 Larkin Divide, Lake Geovanny, Oman,396 Dino Field, Lake Andrew, Botswana,931 Rick Mountains, Lourdesmouth, Mozambique",
                            Released = 2022,
                            Synopsis = "Facilis occaecati a delectus vel sed aut voluptatum. Qui dolor unde quas est voluptas similique maiores. Veritatis sapiente ea quia cum. Ab enim numquam sequi.",
                            Title = "Samson"
                        },
                        new
                        {
                            Id = 82,
                            Genre = "Electronic,Stage And Screen,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "75191 Kihn Cliffs, South Noel, Slovakia (Slovak Republic),9543 Mante Squares, East Aiden, Bermuda,11354 Abshire Oval, New Mose, Cocos (Keeling) Islands",
                            Released = 2023,
                            Synopsis = "Optio ipsam sint voluptatem. Non consequatur at perspiciatis distinctio accusamus dolorem. Aut ducimus voluptatem minus molestiae animi et.",
                            Title = "Kelley"
                        },
                        new
                        {
                            Id = 83,
                            Genre = "Soul,Soul,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "32003 Ruthie Landing, New Hilmatown, Singapore,5063 Schaefer Forges, Wisokychester, Martinique,9481 Blick Court, Larsonton, Timor-Leste",
                            Released = 2022,
                            Synopsis = "Expedita praesentium dolor praesentium voluptatem ut ab ut nostrum voluptatem. Quasi voluptatem recusandae id qui perferendis aut veniam optio officia. Porro autem aut perspiciatis necessitatibus quos. Distinctio et exercitationem id sed blanditiis autem beatae numquam. Consectetur nihil enim culpa non vitae. Voluptas quis quos quo voluptas architecto magnam maxime dignissimos.",
                            Title = "Arnoldo"
                        },
                        new
                        {
                            Id = 84,
                            Genre = "Stage And Screen,Funk,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "305 Maxwell Streets, South Vida, Angola,371 Reva Spur, Millsport, Botswana,0014 Turcotte Prairie, Port Angelfort, France",
                            Released = 2023,
                            Synopsis = "Officiis error eius eius voluptatem. Ea aut quidem. Hic iure quaerat deserunt soluta similique possimus similique maxime. Reprehenderit odit aut sapiente eum facere qui. Omnis cumque optio earum. Doloremque quidem mollitia.",
                            Title = "Josh"
                        },
                        new
                        {
                            Id = 85,
                            Genre = "Metal,Reggae,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "877 Ned Light, West Enoch, Guinea-Bissau,2816 Velva Trail, Lake Rogelio, Nepal,7212 Darryl Throughway, Kundeview, Bolivia",
                            Released = 2023,
                            Synopsis = "Quia facere voluptatum et qui. Aut in facilis. Autem dolor possimus corporis facilis. Nostrum voluptatem rem reprehenderit libero. Ut reiciendis reprehenderit recusandae at et eius et et. Ex similique eos possimus et unde voluptatem.",
                            Title = "Immanuel"
                        },
                        new
                        {
                            Id = 86,
                            Genre = "Funk,Country,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "978 Dangelo Shore, South Mauricioburgh, Wallis and Futuna,50946 Kilback Fall, East Derrickville, Mauritania,588 Ayla Via, South Karlie, Malta",
                            Released = 2023,
                            Synopsis = "Quaerat quibusdam totam. Sunt sit alias sed illo. Placeat sint eum deserunt. Doloremque aliquam pariatur praesentium recusandae dolorum consequatur similique esse. Mollitia dignissimos distinctio provident.",
                            Title = "Brody"
                        },
                        new
                        {
                            Id = 87,
                            Genre = "Rock,Metal,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "430 O'Kon Fields, Tracyburgh, Guernsey,52897 O'Reilly Curve, Port Carminefurt, Macedonia,96010 Sauer Mountains, Sophiahaven, Eritrea",
                            Released = 2022,
                            Synopsis = "Molestiae repudiandae incidunt atque rerum. Nostrum nobis commodi quas ducimus magni ad voluptate. Ducimus quasi enim rem eligendi sit qui expedita.",
                            Title = "Thelma"
                        },
                        new
                        {
                            Id = 88,
                            Genre = "World,Pop,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "398 Daniel Light, Osinskiville, Niger,9267 Jaqueline Ford, Paucekfort, Guam,489 Howe Crescent, Doylemouth, Libyan Arab Jamahiriya",
                            Released = 2022,
                            Synopsis = "Ut perferendis aut eligendi ut dolorem sed repudiandae et occaecati. Maxime voluptatem alias eum nisi sequi animi. Dolores saepe quaerat. Sunt omnis mollitia alias quae dolore enim repellendus. Iure corrupti molestiae.",
                            Title = "Luna"
                        },
                        new
                        {
                            Id = 89,
                            Genre = "Classical,World,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "56906 Maud Parkways, South Taylorborough, Central African Republic,27230 Lafayette Trail, Arthurtown, Egypt,386 Friesen Corner, New Brianport, Virgin Islands, U.S.",
                            Released = 2023,
                            Synopsis = "Et ut quis ex. Rerum quod error ratione et corporis. Sed voluptas at nisi quas provident ab vel quidem non. Tempore distinctio dolor. Doloribus quibusdam dolores veniam deserunt. Sit fugiat dolor.",
                            Title = "Karina"
                        },
                        new
                        {
                            Id = 90,
                            Genre = "Rock,World,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "2612 Briana Ferry, New Janstad, Peru,869 Samanta Field, West Henrihaven, Sierra Leone,314 Kenya Streets, West Lawrence, Holy See (Vatican City State)",
                            Released = 2023,
                            Synopsis = "Quia consequuntur nemo expedita distinctio rerum aspernatur veniam id eveniet. Quis velit ut qui voluptatem voluptatem omnis. Qui est enim cupiditate et voluptates expedita qui. Minus quidem est ex consequuntur aut aperiam dolores sit error. Rerum dolorum rerum architecto dignissimos temporibus. Quo eos nesciunt et et soluta.",
                            Title = "Hadley"
                        },
                        new
                        {
                            Id = 91,
                            Genre = "Jazz,World,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "12064 Larson Rue, East Delphiaborough, Saint Martin,433 Ebba Turnpike, Fishertown, Panama,99152 Sigmund Cape, South Elwynberg, Bolivia",
                            Released = 2022,
                            Synopsis = "Et occaecati omnis quis consequatur. Rerum earum quidem odit explicabo facere repellat optio alias accusamus. Libero quibusdam nisi qui blanditiis quod saepe dolor id. Ex commodi ut nesciunt dignissimos reprehenderit. Alias voluptatem laborum ab sint cumque reprehenderit voluptas et laudantium.",
                            Title = "Noe"
                        },
                        new
                        {
                            Id = 92,
                            Genre = "Metal,Classical,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "4634 Beaulah Mill, South Velda, Colombia,2745 Dixie Village, Lake Juliaberg, Chile,3235 Ledner Dam, Elenorville, Albania",
                            Released = 2023,
                            Synopsis = "Voluptas corporis asperiores similique autem. Accusamus dolores est occaecati impedit. Deserunt officiis illo.",
                            Title = "Jorge"
                        },
                        new
                        {
                            Id = 93,
                            Genre = "Stage And Screen,Soul,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "86736 Bartoletti Parkway, South Benedictfort, Jordan,59358 Chasity Curve, Carafurt, Norway,77895 Alda Field, Port Kraig, Benin",
                            Released = 2023,
                            Synopsis = "Fugit magni dolore dolores non. Nulla asperiores repellat non enim similique. Et harum nostrum quas aut. Debitis voluptates quia.",
                            Title = "Samir"
                        },
                        new
                        {
                            Id = 94,
                            Genre = "Rap,Reggae,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "383 Mellie Street, Millsfurt, Bolivia,25595 Liliane Ridges, East Quincyfort, Vanuatu,05377 Jarod Island, Lake Giles, Austria",
                            Released = 2023,
                            Synopsis = "Molestiae est illo rerum mollitia debitis tempore fugiat dolor inventore. Veniam quia recusandae voluptate nulla voluptatem omnis mollitia non exercitationem. Est ut voluptatem incidunt sint et molestias voluptatem corporis. Nemo facere consequatur. Hic ipsam voluptatem.",
                            Title = "Danyka"
                        },
                        new
                        {
                            Id = 95,
                            Genre = "Hip Hop,Blues,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "445 Bogisich Summit, Liamview, Bermuda,084 Faye Locks, Port Robynstad, Christmas Island,0479 Elfrieda Island, Port Damionport, Belgium",
                            Released = 2023,
                            Synopsis = "Enim voluptatem dolorem a cum earum similique ex. Minima eos omnis ducimus quos fugiat. Est error molestiae explicabo laudantium officia officia adipisci et dicta.",
                            Title = "Ellie"
                        },
                        new
                        {
                            Id = 96,
                            Genre = "Stage And Screen,World,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "0201 Smith Pike, North Domingoview, Ecuador,939 Boyer Isle, Lake Hettiebury, Hungary,8437 Lisa Trace, Yeseniahaven, Uzbekistan",
                            Released = 2023,
                            Synopsis = "Est pariatur culpa. Quia id accusamus voluptatem illum dignissimos omnis officiis voluptatem. Delectus optio suscipit impedit totam voluptatem eos velit eos quo. Ullam assumenda sit qui quia magni. Facilis ex incidunt occaecati occaecati ut. Doloribus velit totam est ipsum asperiores saepe dolorum.",
                            Title = "Destini"
                        },
                        new
                        {
                            Id = 97,
                            Genre = "Jazz,Pop,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "8915 Chris Creek, Lake Brenda, Solomon Islands,7516 Yost Ramp, Camylletown, Moldova,21955 Gorczany Camp, Devanteshire, Saint Vincent and the Grenadines",
                            Released = 2023,
                            Synopsis = "Aut rem consequuntur corrupti velit qui cum corrupti. Dolore reprehenderit qui aut voluptatem nihil dolore. Id et eum explicabo aut magni. Blanditiis commodi repudiandae ea. Molestiae fugiat sit. Ut consequatur sit vitae debitis culpa.",
                            Title = "Florida"
                        },
                        new
                        {
                            Id = 98,
                            Genre = "Reggae,Non Music,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "62279 Heaney Land, Omamouth, Estonia,92474 Una Hill, West Kattieland, Anguilla,646 Hickle Mission, East Kalebtown, Paraguay",
                            Released = 2023,
                            Synopsis = "Aliquam eaque eaque laborum quis repellat. Consequatur omnis assumenda repudiandae nobis autem quis odit tenetur et. Velit est odio quas. Est et rerum architecto nostrum totam deserunt id fuga omnis. Consectetur sunt consectetur.",
                            Title = "Caleb"
                        },
                        new
                        {
                            Id = 99,
                            Genre = "Soul,Folk,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "3037 Boyer Ranch, South Ricardohaven, San Marino,2568 Dach Junction, New Minerva, Kiribati,2567 Murphy Parkways, Lake Erwinton, Republic of Korea",
                            Released = 2023,
                            Synopsis = "Corporis ipsa sint aut ea placeat. Maiores saepe est. Rerum dolores dolor sit deserunt.",
                            Title = "Conrad"
                        },
                        new
                        {
                            Id = 100,
                            Genre = "Electronic,Blues,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "78302 Ernestina Path, Berniermouth, Honduras,33799 DuBuque Stravenue, Beierberg, Solomon Islands,1626 Okuneva Land, Bergeshire, Mayotte",
                            Released = 2023,
                            Synopsis = "Et aut officia corrupti magnam voluptas sequi quisquam iure. Quas ratione praesentium sit est. Non omnis ut. Sint doloribus in quo ullam quisquam sed dignissimos. Nostrum voluptas sed et qui molestias est iste ipsam quo. Accusamus ut itaque eum.",
                            Title = "Ferne"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
