// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230919120651_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<string>("ImdbURL")
                        .HasColumnType("longtext");

                    b.Property<int>("Released")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Pop,Hip Hop,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "20486 Herzog Islands, Johnstonhaven, Lebanon,093 Hand Ridge, Fletahaven, Botswana,50684 Emilie Mountains, Kossshire, Cayman Islands",
                            Released = 2022,
                            Synopsis = "Nihil numquam cupiditate est expedita aut. Debitis aliquid odit. Incidunt aliquam et molestiae nihil dolorem repudiandae voluptas.",
                            Title = "Jeffry"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Electronic,Soul,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "20823 Klein Wall, Port Ralph, Pakistan,4063 Gerhard Shore, Greenfelderborough, Timor-Leste,29568 Emmanuelle Landing, Bergnaumton, Somalia",
                            Released = 2023,
                            Synopsis = "Velit dolor nostrum doloribus quas. Consequatur reprehenderit voluptatem quo necessitatibus ab sed facilis error in. Ipsa officia odit qui. Eum qui qui. Laborum quam vero. Amet adipisci aut aut sequi incidunt magnam neque voluptas quisquam.",
                            Title = "Haven"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Pop,Soul,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "2234 Marjory Centers, South Eve, Montserrat,947 Crystal Canyon, Cierraberg, Gabon,2644 Garnett Prairie, Schmidtshire, Ukraine",
                            Released = 2022,
                            Synopsis = "Officia dignissimos perspiciatis facere facere et eaque voluptas omnis occaecati. Dolores consequatur sed mollitia ut rem nihil. Sunt ut accusantium saepe fugit aliquid. Saepe id assumenda harum amet aut occaecati et dolor. Debitis et ut enim.",
                            Title = "Lydia"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Country,Hip Hop,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "5249 O'Hara Mountains, Brionnastad, Montserrat,0072 Osinski Vista, New Evangeline, Eritrea,38713 Connor Plains, West Kaylah, Bulgaria",
                            Released = 2022,
                            Synopsis = "Commodi temporibus adipisci voluptates ut. Est ut alias placeat magnam dolore. Eos animi qui sit asperiores ipsa architecto. Consequuntur expedita sit culpa laboriosam quis dolores voluptatibus. Id sunt et. Hic ut non qui ullam sit.",
                            Title = "Edmund"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Rap,Soul,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "5324 Bayer Trace, East Maxine, Nauru,54725 Hoyt Estates, Jodiechester, Chad,06957 Scotty Run, Port Bartholome, Turkmenistan",
                            Released = 2023,
                            Synopsis = "Et tempore adipisci. Dolorem voluptatem nisi sapiente et natus occaecati doloremque mollitia. Corrupti architecto aut aut ut.",
                            Title = "Payton"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Jazz,Funk,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "4552 Olson Cliffs, Waelchistad, South Africa,74556 Audie Light, McLaughlinside, Syrian Arab Republic,56654 Cole Meadows, North Jerod, Netherlands Antilles",
                            Released = 2023,
                            Synopsis = "Expedita architecto nihil totam consectetur. Impedit qui possimus reiciendis dolorem necessitatibus aut rerum est voluptas. Dicta quo sed. Autem alias doloremque nostrum molestias aut quibusdam doloremque sit ut. Sit doloremque dolor molestias architecto est. Iusto reprehenderit et aut repellendus.",
                            Title = "Gwendolyn"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Hip Hop,Rap,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "995 Powlowski Plain, Lake Zoe, Denmark,83717 Hansen Terrace, East Sydniefurt, Saint Pierre and Miquelon,5624 Jacobson Point, South Delmermouth, Botswana",
                            Released = 2022,
                            Synopsis = "Officia suscipit sint aut quidem sint. Totam nihil molestiae saepe. Omnis et placeat similique est. Adipisci atque expedita accusamus in nesciunt saepe accusamus amet. Ducimus repudiandae itaque temporibus tempore aut hic.",
                            Title = "Cristal"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Reggae,Country,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "621 Leffler Port, Deckowton, Iceland,19187 Skiles Mountain, Brandtview, Ecuador,20173 Cassin Gateway, South Herminia, Guadeloupe",
                            Released = 2023,
                            Synopsis = "Fugit exercitationem sint aut. Ipsum reiciendis vel voluptas fugit nisi illo ex sint. Quasi eius est et veniam maxime voluptatum et incidunt omnis. Error impedit et officiis aliquam enim consequatur.",
                            Title = "Avery"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Jazz,Hip Hop,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "6242 Ray Village, New Abraham, Afghanistan,88673 Deckow Trafficway, Naderburgh, Sierra Leone,597 O'Keefe Spring, East Eusebiohaven, Comoros",
                            Released = 2022,
                            Synopsis = "Aut earum vitae magnam eum voluptatem facere. Ex voluptas modi cumque ab. Odio distinctio corrupti quas optio doloribus adipisci quae ut veniam. Ut quod laborum. Id iusto voluptas numquam sed ipsam aut qui occaecati.",
                            Title = "Nigel"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Stage And Screen,Country,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "802 Lehner Shore, Clairemouth, Finland,360 Lonzo Knoll, Port Estebanton, Sao Tome and Principe,905 Stan Hills, Hauckchester, Jamaica",
                            Released = 2023,
                            Synopsis = "Delectus consequatur saepe amet sint voluptatem dolores et error in. Quibusdam incidunt et quam. Fuga doloribus sunt qui voluptate voluptates consequatur veniam incidunt. Occaecati inventore eos laborum doloribus doloremque sit explicabo amet velit. Architecto aliquam est eaque dolores sint. Veritatis est veritatis aut eligendi magnam velit unde magnam autem.",
                            Title = "Elliot"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Pop,Folk,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "0273 Winston Ville, Waltonbury, Congo,4274 Roob Mall, Oberbrunnerburgh, Malta,973 Quigley Extension, North Danafurt, Iceland",
                            Released = 2023,
                            Synopsis = "Deserunt inventore deserunt quas eum et sed ea sint. Dolor consectetur nesciunt nam placeat praesentium modi. Delectus quia aut. Impedit voluptatem dolorem illo dolorem esse vel.",
                            Title = "Allison"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Country,Blues,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "3115 Schmitt Gateway, Farrellborough, Sierra Leone,068 Monahan Shores, Lupefurt, Slovakia (Slovak Republic),3601 Arnulfo Vista, Jazmynestad, French Polynesia",
                            Released = 2023,
                            Synopsis = "Quis sint voluptate aut officia dolores corrupti. Quos tempore a deserunt ipsa saepe debitis sed vel aliquid. Dolore facilis repudiandae ut voluptates in veniam. Rerum nulla quos eos beatae ipsa perspiciatis.",
                            Title = "Renee"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Funk,Non Music,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "01030 Douglas Parkways, Lake Kathlyn, Bermuda,878 Verla Prairie, Leuschkeville, Turkey,04472 Roob Spur, Streichborough, Burundi",
                            Released = 2023,
                            Synopsis = "Excepturi voluptatem asperiores nesciunt ullam corporis quisquam ut. Occaecati voluptatibus ea id sunt sequi. Quisquam alias doloremque dicta assumenda sed commodi voluptas repudiandae.",
                            Title = "Haven"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Rap,Folk,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "6341 Hartmann Field, Lake Luciobury, Myanmar,0371 Quigley Lane, North Joelburgh, Marshall Islands,387 Kirlin Keys, New Dillanville, Norway",
                            Released = 2023,
                            Synopsis = "Quo et vitae hic deserunt architecto qui. Ad deserunt itaque consequatur aliquam quo qui rerum qui. Ut est molestiae sint.",
                            Title = "Antoinette"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Soul,Folk,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "22301 Anabelle Parkways, East Cristal, French Polynesia,5714 Kamren Spring, Caitlyntown, Faroe Islands,7095 Walsh Island, Deionmouth, Guatemala",
                            Released = 2022,
                            Synopsis = "Sapiente deleniti qui iste. Nemo velit sed aut ducimus. Distinctio sunt iure quia excepturi quas. Et placeat maxime dolore. Sapiente iste vitae totam illo qui odit laboriosam ab totam.",
                            Title = "Tierra"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Country,Pop,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "20104 Bergnaum Brook, Wilburnfort, Peru,5944 Zemlak Street, Schroederton, Nigeria,81644 Hane Course, New Melody, Uzbekistan",
                            Released = 2022,
                            Synopsis = "Quidem ea molestiae autem aut. Hic aut et eligendi qui ut quod et. Blanditiis eum magnam neque quis et iusto velit et. Et architecto ullam animi id labore voluptatem. Rerum unde consequatur. Nemo accusantium voluptatem id.",
                            Title = "Katelynn"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Stage And Screen,Blues,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "930 Kuvalis Roads, Port Eleanoremouth, Georgia,91854 Roosevelt Court, Konopelskiland, Canada,3145 Daniel Cove, Cormierton, Trinidad and Tobago",
                            Released = 2023,
                            Synopsis = "Explicabo repudiandae modi velit soluta. Ut deleniti est aut corrupti quidem dignissimos dolore voluptas sed. Quo ut ratione voluptatem rerum soluta tempora qui at eum. Nemo adipisci autem rerum neque ratione excepturi quia. Dolor iste sint ullam est labore neque eveniet.",
                            Title = "Mariela"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Country,Latin,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "0835 Howe Underpass, Randalport, Faroe Islands,45503 Schamberger Hills, Port Isaiahville, Tuvalu,4055 Aidan Unions, Lewischester, Turks and Caicos Islands",
                            Released = 2023,
                            Synopsis = "Non ab magni similique sit magnam tenetur similique et. Et eius nihil. Nemo dolorum voluptatem rerum. Molestiae magni omnis est ut aliquam repudiandae vel.",
                            Title = "April"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Reggae,Rap,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "851 Arlene Village, North Lilianeside, Cambodia,8377 Marquardt Cove, McKenzieland, Cyprus,41838 Powlowski Crossing, Caleighport, Czech Republic",
                            Released = 2023,
                            Synopsis = "Pariatur enim nihil voluptatum dolor quia et quia voluptas. Nulla ut a repudiandae laboriosam non quisquam a inventore. Accusantium velit rerum aut nemo blanditiis enim pariatur. Cum ipsam culpa dolorem. Voluptatem ipsam sit.",
                            Title = "Sydnie"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Metal,Latin,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "527 VonRueden Flats, New Noe, British Indian Ocean Territory (Chagos Archipelago),60815 Padberg Ford, Doyleview, Czech Republic,4775 Jake Cape, New Davon, Papua New Guinea",
                            Released = 2023,
                            Synopsis = "Facere ut eius odio. Labore autem ut qui. Temporibus veniam qui esse sit ad deserunt est ducimus velit. Laudantium laborum quia iure sint distinctio.",
                            Title = "Rosalind"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Electronic,Classical,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "3303 Augusta Orchard, East Merle, Palestinian Territory,7113 Jedidiah Meadows, Hermannborough, Nepal,1456 Purdy Via, Jacksonborough, Guyana",
                            Released = 2023,
                            Synopsis = "Dolor velit hic est. Minima quia excepturi labore et commodi sit culpa. Officiis eius facere aperiam enim quibusdam autem dignissimos voluptatem et. Et exercitationem eligendi hic. Ad optio enim laborum necessitatibus laudantium aut tenetur aut harum.",
                            Title = "Gustave"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Blues,Soul,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "4083 Gleichner Port, East Jeraldshire, Malawi,2435 Armand Throughway, Barrowstown, Gibraltar,066 Dejah Junctions, Port Barneyborough, Norfolk Island",
                            Released = 2022,
                            Synopsis = "Eos amet est sed magnam excepturi omnis aperiam. Impedit blanditiis laboriosam dolorem vero beatae aperiam nisi in. Quia non dolores eos blanditiis et necessitatibus quo. Tempora delectus corrupti hic.",
                            Title = "Durward"
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Folk,Latin,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "28196 Reilly Lake, Kovacekport, Mauritius,25076 Ericka Islands, Hankville, Slovenia,316 Isom Tunnel, Mittieville, Colombia",
                            Released = 2023,
                            Synopsis = "Blanditiis optio quis aut nam voluptatum molestias fuga. Nisi et ut voluptate est. Qui quibusdam delectus consequatur.",
                            Title = "Neal"
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Classical,Non Music,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "20651 Schumm Spring, Luciostad, Albania,63128 Furman Spurs, Port Raymundoberg, Mayotte,42855 Melyssa Valleys, Oletaside, Niger",
                            Released = 2023,
                            Synopsis = "Exercitationem recusandae et et sapiente aut id eos. Dolor minima aut ex. Et voluptatum fugiat labore qui et neque alias provident. Nam possimus laborum incidunt ipsum et et enim. Dicta laboriosam distinctio qui sequi ut reiciendis ut excepturi est. Sunt quia blanditiis exercitationem.",
                            Title = "Zella"
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Stage And Screen,Funk,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "834 Rafael Meadows, Mohammadland, Uruguay,6280 Cruickshank Fork, Lake Dayanafurt, Norway,91303 Zieme Viaduct, Lake Pete, Armenia",
                            Released = 2023,
                            Synopsis = "Ea dicta voluptatibus nesciunt suscipit a temporibus expedita aut. Qui laborum eum perferendis error et. Facilis voluptas dolore perferendis.",
                            Title = "Zetta"
                        },
                        new
                        {
                            Id = 26,
                            Genre = "Latin,World,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "94437 Lloyd Locks, Lake Kaelabury, South Georgia and the South Sandwich Islands,854 Bergnaum Shoal, Rogersshire, Ecuador,98810 Kovacek Hollow, Murazikbury, Sri Lanka",
                            Released = 2022,
                            Synopsis = "Sit tempore facere optio at numquam ipsa ad repellat. Laboriosam rerum cumque. Consequatur itaque sit beatae sed odio. Reprehenderit ut sit adipisci sed et animi. Ut quia dicta neque dolores corporis veniam.",
                            Title = "Alisha"
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Jazz,World,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "9937 Callie Expressway, Nolanfurt, Bosnia and Herzegovina,4470 Kling Mews, Prohaskaport, Niger,177 Schneider Dale, South Juliusview, Suriname",
                            Released = 2022,
                            Synopsis = "Aut exercitationem sed et assumenda quo cum nihil. Fugit velit corrupti nostrum quam praesentium. Delectus voluptatem non eveniet.",
                            Title = "Dawson"
                        },
                        new
                        {
                            Id = 28,
                            Genre = "Non Music,Pop,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "560 Gleason Village, Lake Monty, Lebanon,924 Antonina Vista, Marksmouth, Liechtenstein,028 Rogahn Walk, Phoebechester, Papua New Guinea",
                            Released = 2023,
                            Synopsis = "Quasi natus voluptatum maiores dolores asperiores illum. Eaque autem accusantium omnis quia amet ut. Sunt cum architecto iure sed. Facere rerum sit molestiae eum adipisci.",
                            Title = "Rhiannon"
                        },
                        new
                        {
                            Id = 29,
                            Genre = "Electronic,Folk,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "71094 Mann Heights, West Deltahaven, Oman,9025 Howell Port, Runolfssonchester, Finland,05342 Koelpin Underpass, Baileyberg, Andorra",
                            Released = 2023,
                            Synopsis = "Quis magni temporibus totam dolor itaque. Quae itaque dolores doloribus aliquid quis. Quo repellat est ea nulla nihil quo maiores sunt.",
                            Title = "Jaunita"
                        },
                        new
                        {
                            Id = 30,
                            Genre = "Electronic,Pop,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "743 Schroeder Stream, McKenzieborough, Guatemala,07492 Funk Meadows, Charitymouth, British Indian Ocean Territory (Chagos Archipelago),7556 Aaron Union, Koelpintown, Belize",
                            Released = 2023,
                            Synopsis = "Quo exercitationem fugiat. Eligendi fuga in nam id. Eos ut aut autem recusandae a. Quos libero id illo mollitia saepe amet. Dicta voluptas voluptate consectetur. Voluptates eos quod rem necessitatibus nihil.",
                            Title = "Felicity"
                        },
                        new
                        {
                            Id = 31,
                            Genre = "Country,Country,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "2101 Haylie Dale, North Jeramiemouth, Antarctica (the territory South of 60 deg S),161 Kelvin Roads, Evaburgh, Mozambique,716 Max Oval, Port Ludie, Virgin Islands, U.S.",
                            Released = 2023,
                            Synopsis = "Pariatur rerum doloremque pariatur ipsum. Odit laborum aut. Sint et ut cum corporis maxime quo enim sequi iusto. Qui quis praesentium. Ut quis aut illo eum labore saepe non ipsam commodi.",
                            Title = "Mireya"
                        },
                        new
                        {
                            Id = 32,
                            Genre = "Folk,Rock,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "2840 Nicholaus Hill, Nienowton, Costa Rica,822 McCullough Course, Earnestineton, Austria,9517 Emmerich Ways, Port Charleyton, Turkmenistan",
                            Released = 2023,
                            Synopsis = "Fuga debitis officia excepturi ab fugiat harum voluptatem repellendus assumenda. Provident sapiente blanditiis voluptatem est laudantium rerum. Labore sit qui consequatur beatae inventore iusto qui dolor. Autem quis velit esse similique. Et et in minima qui quibusdam id optio distinctio quia. Quis totam tempora.",
                            Title = "Laila"
                        },
                        new
                        {
                            Id = 33,
                            Genre = "Soul,Funk,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "97266 Zemlak Point, South Ron, Equatorial Guinea,3987 Angela Port, Jacintomouth, Spain,92604 Prosacco Crossroad, Port Woodrow, Serbia",
                            Released = 2023,
                            Synopsis = "Quas mollitia perspiciatis sint. Non itaque repudiandae dolorum aut consequuntur quae expedita soluta soluta. Et amet earum. Officiis quia molestiae.",
                            Title = "Claudia"
                        },
                        new
                        {
                            Id = 34,
                            Genre = "Jazz,Stage And Screen,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "41754 Russel Courts, Bernierberg, Palestinian Territory,7877 Reichel Flats, Wilkinsonview, Heard Island and McDonald Islands,14778 Vergie Mission, Stromanville, Armenia",
                            Released = 2023,
                            Synopsis = "Suscipit amet et facere incidunt. Quis et quod ut. Possimus dicta optio neque omnis illo aut error officiis. Quasi ipsum et laborum.",
                            Title = "Winifred"
                        },
                        new
                        {
                            Id = 35,
                            Genre = "Non Music,Classical,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "5418 Raynor Locks, Christiansenstad, Estonia,9605 Axel Avenue, Maynardburgh, New Zealand,9082 Carrie Island, Leannfurt, Tuvalu",
                            Released = 2023,
                            Synopsis = "Unde blanditiis quisquam ipsa odit nam. Animi dolor aut qui ea enim voluptatibus. Et quia praesentium doloremque saepe pariatur voluptatem qui earum dolor. Explicabo consequatur dolore eaque temporibus maiores rerum aliquid. Aut qui dignissimos molestias aut.",
                            Title = "Ora"
                        },
                        new
                        {
                            Id = 36,
                            Genre = "Pop,Blues,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "407 Marisol Crescent, Gibsonfort, Brunei Darussalam,6613 Madisyn Manor, Lake Carrie, Malaysia,9094 Winfield Rapid, Parisianside, Azerbaijan",
                            Released = 2023,
                            Synopsis = "Alias dolor temporibus voluptas nobis culpa autem error eos repellendus. Porro repellat ipsam perspiciatis consectetur distinctio. Eum id facere veniam. Occaecati repudiandae mollitia et necessitatibus. Sequi veniam quia voluptatibus nulla sapiente occaecati quidem molestias.",
                            Title = "Daron"
                        },
                        new
                        {
                            Id = 37,
                            Genre = "Latin,Country,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "836 Annamae Tunnel, New Jayme, Uruguay,2872 Ritchie Locks, Audreyfort, Ukraine,61560 Brown Cove, South Maximilliaton, United Kingdom",
                            Released = 2023,
                            Synopsis = "Incidunt id voluptatem pariatur ad deserunt natus aut. Aut et voluptatem reprehenderit quas sit quis qui enim libero. Tenetur vel aut. Sequi et magni iure rerum ea iure in.",
                            Title = "Afton"
                        },
                        new
                        {
                            Id = 38,
                            Genre = "World,Reggae,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "246 Dayne Neck, New Dereckfurt, South Georgia and the South Sandwich Islands,2579 Forest Lodge, Mitchellville, Vietnam,1520 Meda Station, Hayesmouth, Belgium",
                            Released = 2023,
                            Synopsis = "Non molestiae sapiente delectus. Nobis non et deserunt. Magnam suscipit in omnis dolor. Recusandae unde quasi quis officia sunt. Nemo consequatur sunt sit sint et sed earum accusantium consequatur.",
                            Title = "Furman"
                        },
                        new
                        {
                            Id = 39,
                            Genre = "Jazz,Reggae,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "661 Destinee Squares, South Jackychester, Maldives,18000 Rowe Village, Lake Cobyville, Singapore,0611 Kirstin Springs, Lake Adolph, Australia",
                            Released = 2023,
                            Synopsis = "Aut quo aperiam rerum et. Voluptatum cupiditate est fugit voluptatum sapiente minus labore odio consequatur. Nisi nihil cumque laborum in.",
                            Title = "Magali"
                        },
                        new
                        {
                            Id = 40,
                            Genre = "World,Stage And Screen,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "047 Swift Mission, Quigleyville, South Africa,2922 McCullough Streets, Myrlport, Morocco,950 McGlynn Prairie, Nicklausmouth, Belgium",
                            Released = 2023,
                            Synopsis = "Totam suscipit eum exercitationem. Quia similique doloremque eligendi provident tempora. Autem porro dolorum a sit earum. Omnis occaecati optio voluptas. Molestias sapiente nesciunt voluptate.",
                            Title = "Brady"
                        },
                        new
                        {
                            Id = 41,
                            Genre = "Pop,Classical,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "29606 Kayley Spur, South Earnestineberg, Montenegro,89544 Schmidt Highway, Lake Patsy, Spain,64053 Kuhn Corner, Lednershire, Denmark",
                            Released = 2022,
                            Synopsis = "Ipsa autem quidem perspiciatis. Reiciendis quidem exercitationem qui enim qui beatae dignissimos reiciendis voluptas. Nam illo dolor quos eius velit porro.",
                            Title = "Giovanny"
                        },
                        new
                        {
                            Id = 42,
                            Genre = "Non Music,Electronic,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "91291 Runte Forks, Purdyville, American Samoa,72480 Batz Station, South Adahland, Spain,518 Abdul Pike, Shanahantown, Micronesia",
                            Released = 2023,
                            Synopsis = "Sed cum minima rerum asperiores animi tempore. Iste praesentium ut debitis magnam est ut laboriosam minus. Autem sit blanditiis iste quidem eius praesentium velit. Ut voluptatem dolorum molestias magni doloribus qui dicta. Eum quis quos nesciunt id qui est.",
                            Title = "Hipolito"
                        },
                        new
                        {
                            Id = 43,
                            Genre = "Country,Funk,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "400 Bergnaum Mountains, South Darwin, Kiribati,010 Feest Ford, Port Alyson, Palestinian Territory,63921 Reinger Spurs, Runolfssonshire, Pitcairn Islands",
                            Released = 2022,
                            Synopsis = "Recusandae sit consequatur excepturi dolore officia. Voluptatem sint aspernatur consequatur et sequi. Ut magnam quia eos quod et. Et alias quis cum laborum qui.",
                            Title = "Maud"
                        },
                        new
                        {
                            Id = 44,
                            Genre = "Funk,Jazz,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "322 Paucek Landing, West Nicholechester, Monaco,78701 Aletha Ridge, Nayeliborough, Guinea,08408 Lowe Rapid, Stehrchester, Holy See (Vatican City State)",
                            Released = 2023,
                            Synopsis = "Quia deserunt sit magni et ad impedit sunt nobis. Quisquam provident dolore ut molestiae dolorum aspernatur eveniet. Ab nemo explicabo recusandae quo. Nobis modi cumque iste sit ipsam minus. Consequatur cumque minus temporibus qui ab voluptas necessitatibus odio. Quas qui et voluptas quia eos voluptatibus aut.",
                            Title = "Aliza"
                        },
                        new
                        {
                            Id = 45,
                            Genre = "Funk,Folk,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "324 Keyon Fords, North Cristalmouth, Bulgaria,305 Kaylah Stream, North Xavier, Sao Tome and Principe,94260 Crooks Place, Claudieville, El Salvador",
                            Released = 2023,
                            Synopsis = "Est aut esse mollitia magnam est repudiandae laboriosam nesciunt. Illum qui accusamus omnis qui ipsa aut qui nihil cupiditate. Perspiciatis ducimus harum qui. At quos dicta natus pariatur quia quo perspiciatis quos perspiciatis. Dignissimos laudantium hic quaerat ad cupiditate sunt cupiditate. Qui optio facere delectus.",
                            Title = "Cortney"
                        },
                        new
                        {
                            Id = 46,
                            Genre = "Soul,Classical,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "75218 Larkin Springs, East Cary, Kiribati,929 Osinski Court, New Janetside, Belarus,624 Reinger Brooks, Cordeliafort, Montserrat",
                            Released = 2023,
                            Synopsis = "Quod repellat in. Nesciunt beatae repudiandae ipsam labore molestiae sunt vero nihil. Est asperiores ea laudantium et et suscipit doloribus voluptas. Earum nam velit voluptatem non.",
                            Title = "Jovani"
                        },
                        new
                        {
                            Id = 47,
                            Genre = "Pop,Stage And Screen,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "26052 Aufderhar Fort, Yostport, San Marino,80276 Eveline Oval, Marvinburgh, French Southern Territories,041 Fadel Island, Hartmannmouth, Yemen",
                            Released = 2023,
                            Synopsis = "Voluptatem minus laboriosam quibusdam eius voluptas. Distinctio at beatae voluptas a fugit aspernatur ea harum. Ipsum ea et repudiandae illum dolorem vitae cupiditate possimus.",
                            Title = "Vincenza"
                        },
                        new
                        {
                            Id = 48,
                            Genre = "World,Funk,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "7206 Antonina Common, Schoenville, Nepal,105 Bradly Manors, Beckerstad, Saint Martin,5471 Corkery Crossroad, Simeonbury, Syrian Arab Republic",
                            Released = 2022,
                            Synopsis = "Soluta tempore blanditiis minima similique hic illum rerum delectus. Qui eos atque deleniti sunt nesciunt ut dolores. Nobis ea eum.",
                            Title = "Gennaro"
                        },
                        new
                        {
                            Id = 49,
                            Genre = "Reggae,Pop,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "4245 Joan Island, East Dillanville, Bahamas,156 Isaiah Flats, Xzavierbury, Bosnia and Herzegovina,21635 Douglas Crossroad, Hilpertview, Marshall Islands",
                            Released = 2022,
                            Synopsis = "Sequi quos numquam. Tempore quam et qui libero omnis dolorum unde veritatis delectus. Totam omnis harum.",
                            Title = "Caterina"
                        },
                        new
                        {
                            Id = 50,
                            Genre = "Country,Country,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "0110 Ortiz Turnpike, Klingland, Hong Kong,3510 Prosacco Islands, Vincestad, Heard Island and McDonald Islands,97682 O'Hara Keys, Jedidiahside, Samoa",
                            Released = 2023,
                            Synopsis = "Ut dicta autem omnis facere velit. Quis ipsam ut est dolorem nostrum explicabo facere reiciendis eum. Fugit excepturi natus eius.",
                            Title = "Rosamond"
                        },
                        new
                        {
                            Id = 51,
                            Genre = "Stage And Screen,Jazz,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "532 Weissnat Circle, Lake Henriette, Moldova,511 Johnpaul Hill, Vanessastad, Congo,34377 Zakary Road, Merlton, El Salvador",
                            Released = 2023,
                            Synopsis = "Asperiores velit ipsum voluptatum ea ullam quaerat. Nisi est natus non vitae dolor quo ut perspiciatis. In aut magni consequuntur nulla natus nihil accusamus ut. Fuga veniam modi quisquam. Non laboriosam voluptas quia tempora reprehenderit unde consequatur nam explicabo. Saepe quas voluptas in corporis quo.",
                            Title = "Kasandra"
                        },
                        new
                        {
                            Id = 52,
                            Genre = "Pop,Jazz,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "3662 Dewayne Light, West Salvador, Belgium,7538 River Ports, South Evechester, Georgia,698 Veda Ferry, Pfannerstillshire, Mexico",
                            Released = 2023,
                            Synopsis = "Animi eveniet temporibus sit at veritatis qui quis ut inventore. Dolorum officiis aliquid illum praesentium exercitationem cupiditate ipsum enim. Quis et ex ea modi natus sequi cumque. Rerum est voluptates.",
                            Title = "Karina"
                        },
                        new
                        {
                            Id = 53,
                            Genre = "Reggae,World,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "76578 Darian Lock, Lake Romaview, Malawi,679 Blake Estate, New Ronmouth, Tanzania,706 Zemlak Lane, West Ashleigh, Uruguay",
                            Released = 2023,
                            Synopsis = "Corporis qui ea minus porro sequi quis qui sed ipsum. Soluta voluptatem inventore veniam sunt vel qui et. Hic laudantium non veritatis aut eaque veritatis. Odio qui aut quaerat error accusantium qui consectetur ab aperiam. Itaque dicta maxime qui.",
                            Title = "Kathryne"
                        },
                        new
                        {
                            Id = 54,
                            Genre = "Electronic,Country,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "17699 Percy Fort, Port Araceliport, Moldova,51824 Dexter Corners, Lake Budchester, Mexico,81622 Botsford Route, Boehmton, Saint Kitts and Nevis",
                            Released = 2023,
                            Synopsis = "Officia eligendi minus quia repellendus quia. Qui maxime in vel saepe rerum dolor excepturi rem. Eius pariatur quibusdam id repellat et aperiam. Exercitationem totam nostrum iste sed aut officiis. Laboriosam sunt exercitationem dolorem amet. Non suscipit reiciendis cupiditate provident.",
                            Title = "Jaquelin"
                        },
                        new
                        {
                            Id = 55,
                            Genre = "Latin,Rap,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "1792 Natasha Shores, Stoltenbergborough, Norway,680 Bridgette Cape, Maybellefurt, Democratic People's Republic of Korea,341 Runte Station, Port Rylan, Democratic People's Republic of Korea",
                            Released = 2022,
                            Synopsis = "Autem omnis rerum nisi eos autem veritatis iure qui itaque. Ut similique illo suscipit fugiat iste quae delectus. Delectus qui a consequatur aut rerum expedita id. Voluptatum omnis perferendis assumenda.",
                            Title = "Creola"
                        },
                        new
                        {
                            Id = 56,
                            Genre = "Rock,Jazz,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "410 Gordon Forge, East Norrisborough, Greece,245 Meaghan Well, Port Rico, Tajikistan,05695 Kaylah Port, Hickleburgh, Saint Barthelemy",
                            Released = 2023,
                            Synopsis = "Vel minus tempora sapiente quia ut. Quo porro qui qui qui iusto et non. Ut et enim aut aliquam distinctio atque. Mollitia voluptatem qui voluptates molestiae consequuntur quia.",
                            Title = "Lizeth"
                        },
                        new
                        {
                            Id = 57,
                            Genre = "World,Pop,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "2036 Purdy Springs, Johannachester, Tunisia,02487 Conn Meadow, South Maceyland, Northern Mariana Islands,99031 Kristofer Summit, Schadenborough, China",
                            Released = 2022,
                            Synopsis = "Saepe omnis sit dignissimos odio vitae ut. Cupiditate consequuntur minima incidunt facilis omnis. Quas accusantium nostrum consequatur voluptate ea fugiat sapiente. Qui praesentium rem rerum qui aut dolore quae sint. Ut eum molestiae doloribus nobis est dolores illum exercitationem.",
                            Title = "Micaela"
                        },
                        new
                        {
                            Id = 58,
                            Genre = "Folk,Folk,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "4087 Anderson Fork, East Jeramiefort, Cayman Islands,368 Tatyana Ways, Lockmanland, Ecuador,3207 Daphnee Trafficway, Lambertfort, Republic of Korea",
                            Released = 2023,
                            Synopsis = "Ab officiis eveniet reiciendis quae veniam. Ab qui dolore doloremque hic ipsa. Animi reprehenderit perferendis excepturi blanditiis. Autem quis eos.",
                            Title = "Jeffry"
                        },
                        new
                        {
                            Id = 59,
                            Genre = "World,Folk,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "31337 Rory Extensions, Nicolasfort, Virgin Islands, U.S.,4884 Mayert Harbors, West Eloise, United Kingdom,980 Molly Meadows, Guillermoville, Guadeloupe",
                            Released = 2023,
                            Synopsis = "Praesentium et minima sed dolorem voluptatem saepe beatae. Non eligendi ut eum consequuntur dolore ut ab et corrupti. Laboriosam qui facere maxime minima aut. Non totam est nihil sunt accusamus ut ad consequuntur. Eligendi deleniti commodi odio repellendus quae assumenda. Explicabo quasi rerum quas qui officia quis.",
                            Title = "Freddie"
                        },
                        new
                        {
                            Id = 60,
                            Genre = "Stage And Screen,Rap,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "2736 Cummerata Knolls, Yasminefort, Falkland Islands (Malvinas),741 Dean Tunnel, New Thelma, French Southern Territories,6080 Karson Roads, West Libbie, Namibia",
                            Released = 2022,
                            Synopsis = "Id in rem deleniti aut incidunt qui eius earum iure. Rem et tempore rerum. Ut et consequatur dolor omnis mollitia omnis. Aut unde perferendis aut tempora quis itaque corporis. Esse aut pariatur saepe. Veniam quasi incidunt sit in ut dignissimos quia ipsa.",
                            Title = "Dennis"
                        },
                        new
                        {
                            Id = 61,
                            Genre = "Hip Hop,Rock,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "043 Ansley Green, Rogahnborough, Barbados,6097 Blick Loop, Emeraldmouth, Guatemala,9326 Glenda Station, Port Joellefort, Aruba",
                            Released = 2023,
                            Synopsis = "Accusantium repellat minus aut ullam vel exercitationem velit sit harum. Tenetur inventore soluta omnis. Facere necessitatibus assumenda. Optio nam vel et laborum aut. Impedit non suscipit rerum eaque. Eaque natus atque eligendi eius est minus qui laudantium consequatur.",
                            Title = "Kaelyn"
                        },
                        new
                        {
                            Id = 62,
                            Genre = "Jazz,Metal,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "18244 Tromp Light, West Huldabury, Antarctica (the territory South of 60 deg S),84459 Gislason Ville, North Rasheed, Jersey,70277 Leffler Station, Bayleehaven, Nicaragua",
                            Released = 2023,
                            Synopsis = "Quo eligendi amet atque doloremque ut accusantium. Ducimus quia placeat perspiciatis sint eligendi aliquam ratione eos occaecati. Aut laborum et aliquam saepe eligendi quisquam tenetur eius. Dolor sit laborum similique a recusandae alias. Ut dolorum nobis placeat occaecati aut quia.",
                            Title = "Zachary"
                        },
                        new
                        {
                            Id = 63,
                            Genre = "Soul,Rock,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "5817 Rosa Fords, Hintzstad, Georgia,4926 Coty Locks, Jonesfurt, Mali,6479 Kemmer Island, Connmouth, Czech Republic",
                            Released = 2023,
                            Synopsis = "Ut rerum ut voluptatem quibusdam est labore voluptatem. Cum molestiae voluptatem commodi et. Libero qui sit ut necessitatibus maiores voluptas et quod assumenda. Nisi corrupti qui. Est est nesciunt expedita excepturi iure magnam. Quidem accusamus enim ipsa et enim beatae voluptate.",
                            Title = "Torrance"
                        },
                        new
                        {
                            Id = 64,
                            Genre = "Folk,Blues,Electronic",
                            ImdbRating = 7.4f,
                            ImdbURL = "02850 Aiyana Fork, North Bertrand, Rwanda,099 Garland Junction, Port Esteban, Northern Mariana Islands,402 Kilback Common, Meggietown, Saudi Arabia",
                            Released = 2023,
                            Synopsis = "Animi et quo neque. Quis non doloremque accusamus ea. Quis asperiores veniam.",
                            Title = "Zetta"
                        },
                        new
                        {
                            Id = 65,
                            Genre = "Non Music,Hip Hop,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "844 Dare Camp, Jeramymouth, Guyana,9215 Leannon Crossing, Sophieport, French Guiana,847 Jewel Trail, Port Joaquin, Jersey",
                            Released = 2023,
                            Synopsis = "Delectus natus excepturi. Ut et fugiat. Beatae beatae ipsa at adipisci molestias illo commodi. Voluptatem quia voluptatibus libero molestiae dolorem. Nihil est sed id et eos consectetur dolore.",
                            Title = "Cydney"
                        },
                        new
                        {
                            Id = 66,
                            Genre = "Latin,Funk,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "9346 Mason Passage, Port Lavonne, Uzbekistan,3184 Pearl Stravenue, Port Jose, Macedonia,4734 Emerson Cape, East Alfredo, Senegal",
                            Released = 2022,
                            Synopsis = "Rerum aliquid impedit dolores quo aliquid vel eos ea dolore. Inventore ut at. Suscipit quod id atque facilis et. Suscipit ut labore hic vitae temporibus cumque et error rerum.",
                            Title = "Newton"
                        },
                        new
                        {
                            Id = 67,
                            Genre = "Electronic,Pop,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "8781 Elouise Turnpike, Halvorsonburgh, Costa Rica,6229 Gottlieb Bypass, New Norvalfort, Senegal,082 Feest Key, West Vincenza, Isle of Man",
                            Released = 2022,
                            Synopsis = "Quo sit perferendis. Et et voluptas aperiam vero quidem autem quia omnis qui. Nihil voluptatem voluptatem deserunt.",
                            Title = "Dandre"
                        },
                        new
                        {
                            Id = 68,
                            Genre = "Rock,Metal,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "90315 Rau Lake, Jaunitachester, Turkey,38296 Schiller Falls, Hansenbury, Mauritius,76778 Blair Crescent, Jadonburgh, Saint Helena",
                            Released = 2023,
                            Synopsis = "Possimus vero nostrum occaecati molestias et aut architecto expedita. Dolor distinctio est omnis eos molestias nihil ullam laborum dolorem. Consectetur odio voluptatibus optio molestias eos consequatur aut maxime distinctio.",
                            Title = "Gino"
                        },
                        new
                        {
                            Id = 69,
                            Genre = "Latin,Country,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "23411 Klocko Cove, Destinichester, Swaziland,52020 Felipe Pines, East Jenabury, Bahrain,63096 Aufderhar River, Faetown, Nauru",
                            Released = 2023,
                            Synopsis = "Omnis veniam et ipsa iure nemo repellendus. Est facilis sit reprehenderit cupiditate quos est. Laboriosam qui accusantium. Aliquam ut nemo eaque voluptas explicabo. Fugit aliquid dolores eveniet voluptas numquam ullam. Omnis rerum sed enim ipsum quia.",
                            Title = "Norene"
                        },
                        new
                        {
                            Id = 70,
                            Genre = "Blues,Blues,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "865 Jettie Skyway, Port Don, Moldova,4160 Sandra Mountains, Friedaton, Nicaragua,47787 Gretchen Knoll, New Lindastad, Paraguay",
                            Released = 2023,
                            Synopsis = "Voluptatem quo nesciunt earum eum qui animi. Ut veritatis rem animi ipsum voluptatem quas sapiente earum. Eum porro nobis eum.",
                            Title = "Nedra"
                        },
                        new
                        {
                            Id = 71,
                            Genre = "Rap,Hip Hop,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "9198 Griffin Summit, New Kenyattahaven, Angola,31374 Abbott Isle, Funkstad, Nauru,7031 Adams Brooks, Shannonborough, Lebanon",
                            Released = 2023,
                            Synopsis = "Rerum qui ab eos dolorem quaerat id. Tempora dolorum sit eum ut atque exercitationem. Eius incidunt laudantium eius doloribus est.",
                            Title = "Coty"
                        },
                        new
                        {
                            Id = 72,
                            Genre = "Jazz,Jazz,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "805 Araceli Square, Starkborough, Cambodia,984 Wisozk Drive, South Augustus, Honduras,4737 Dangelo Well, New Helgaton, Turks and Caicos Islands",
                            Released = 2022,
                            Synopsis = "Dolores eos possimus laudantium quia. Mollitia praesentium ex sit necessitatibus aut dignissimos quaerat suscipit sit. Consequatur inventore illo dolorum laudantium dolorem. Itaque quas voluptatem impedit repellendus.",
                            Title = "Maryjane"
                        },
                        new
                        {
                            Id = 73,
                            Genre = "Rock,World,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "133 McClure Meadow, West Jamesonmouth, Tajikistan,753 Willms Common, South Justyn, Madagascar,0726 Ursula Lights, Jaleelshire, Guam",
                            Released = 2023,
                            Synopsis = "Eius vel ut libero. Laboriosam quam non molestiae similique itaque. Occaecati est odio quam aspernatur consequuntur.",
                            Title = "Jeffrey"
                        },
                        new
                        {
                            Id = 74,
                            Genre = "Hip Hop,Stage And Screen,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "806 Lynn Glen, New Travon, Ukraine,55044 Rolfson Flats, Port Casimir, United States of America,213 Kelley Village, Ullrichport, Turkey",
                            Released = 2022,
                            Synopsis = "Debitis vel ut quisquam dolores id explicabo facere. Est deserunt corrupti et ut. In id sit et ratione deleniti mollitia alias. Ea ipsam minus et in deserunt facilis.",
                            Title = "Gerhard"
                        },
                        new
                        {
                            Id = 75,
                            Genre = "Non Music,Country,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "914 Kacey Cape, Deannatown, Libyan Arab Jamahiriya,35097 Jacobi Manors, Daughertyville, Slovenia,70914 Breitenberg Lights, East Madalyn, Gabon",
                            Released = 2023,
                            Synopsis = "Recusandae voluptates aut. Id quo voluptatem. Quas quis qui sunt et est deserunt iusto exercitationem necessitatibus. Sit similique ut.",
                            Title = "Nettie"
                        },
                        new
                        {
                            Id = 76,
                            Genre = "Hip Hop,Rap,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "7935 Kelsi Harbors, Emilioside, Puerto Rico,315 Mackenzie Dale, Lake Brockshire, Tunisia,47565 Hamill Wells, Jacobibury, Honduras",
                            Released = 2022,
                            Synopsis = "Sunt iure impedit. Facere aut aut perspiciatis aut iure. Molestiae voluptates sunt consequuntur. Sed nostrum perspiciatis eum molestias sed voluptatem ut.",
                            Title = "Sterling"
                        },
                        new
                        {
                            Id = 77,
                            Genre = "Metal,Electronic,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "920 Meaghan Islands, Lucilestad, Bahamas,24924 Tiara River, Luellaville, Indonesia,799 Adolf Crossroad, Millerchester, Panama",
                            Released = 2023,
                            Synopsis = "Consequatur neque pariatur. Voluptatem fugiat reprehenderit autem. Iure ex fugiat aut eligendi quia deleniti et aut qui.",
                            Title = "Neal"
                        },
                        new
                        {
                            Id = 78,
                            Genre = "Jazz,Metal,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "410 Dooley Flats, Mrazville, Guyana,08395 Steuber Squares, Port Justen, Andorra,6035 Veum Isle, New Lucienne, Ireland",
                            Released = 2023,
                            Synopsis = "Laudantium qui ex tempora consequatur optio accusantium odio. Eum officia soluta laboriosam culpa sunt architecto et saepe unde. Omnis dolor aut nihil dolorum et quas explicabo nihil optio. Soluta magni necessitatibus iste debitis pariatur. Laborum distinctio et qui voluptatem accusamus totam aut est exercitationem.",
                            Title = "Kiarra"
                        },
                        new
                        {
                            Id = 79,
                            Genre = "Latin,Soul,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "7602 Erika Corner, East Steve, India,071 Jay Road, West Sheamouth, Swaziland,84629 Tracy Islands, East Louisaton, Haiti",
                            Released = 2022,
                            Synopsis = "Maxime velit in amet eum rerum. Doloremque et dolore ut. Voluptatem ut vero illum ab.",
                            Title = "Olen"
                        },
                        new
                        {
                            Id = 80,
                            Genre = "Hip Hop,Pop,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "5781 Kevon Corner, West Fred, Macao,4351 Kerluke Meadows, Lake Hazelview, Solomon Islands,1278 Alexandre Spurs, Alexandreafort, Norfolk Island",
                            Released = 2023,
                            Synopsis = "Qui magnam non esse sed autem. Ratione nulla quidem accusamus et totam aut aliquam fuga. Minima deleniti veritatis aliquid non voluptas eum dolor aliquam consequatur.",
                            Title = "Earl"
                        },
                        new
                        {
                            Id = 81,
                            Genre = "Blues,World,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "1288 Garland Burg, Ryleyberg, Ecuador,42211 Tabitha Circle, Hillsborough, Spain,78290 Ruecker Alley, Vidalville, Georgia",
                            Released = 2023,
                            Synopsis = "Doloremque saepe cupiditate quis. Corporis ipsa tenetur quia dolores ipsa ad minus. In nihil ratione. Et nam id voluptates eaque quae facere aut.",
                            Title = "Russell"
                        },
                        new
                        {
                            Id = 82,
                            Genre = "Pop,Latin,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "574 Violet View, Elfriedaport, Burundi,79767 Harvey Stravenue, West Derek, American Samoa,8288 Tessie Freeway, Lake Narciso, Falkland Islands (Malvinas)",
                            Released = 2022,
                            Synopsis = "Dolor blanditiis sed cumque laborum sit. Error omnis molestias ea ut ea facilis ea. Et nesciunt omnis odit. Ipsam voluptatem cumque magnam. Dolorem ea excepturi odit dolores quia necessitatibus non velit.",
                            Title = "Brianne"
                        },
                        new
                        {
                            Id = 83,
                            Genre = "Jazz,Stage And Screen,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "2724 Prosacco Stream, Schmittfurt, Maldives,709 Joy Forges, Baumbachhaven, Uzbekistan,764 Crooks Mews, Ofeliaberg, Jersey",
                            Released = 2022,
                            Synopsis = "Tempora id delectus ea. Quia et porro eos placeat est voluptatem. Sit dicta eum fugit labore est voluptatem.",
                            Title = "Araceli"
                        },
                        new
                        {
                            Id = 84,
                            Genre = "Latin,Rap,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "645 Virgie Drive, Port Bonnie, Burundi,35116 Gottlieb Center, Armaniland, Vietnam,236 Rose Squares, Langburgh, Panama",
                            Released = 2023,
                            Synopsis = "At deserunt cupiditate veritatis omnis assumenda sequi consectetur. Ut velit consectetur velit dolorum. Dolores ipsa natus aut aliquam nam vel quo modi.",
                            Title = "Ola"
                        },
                        new
                        {
                            Id = 85,
                            Genre = "Rap,Soul,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "73737 Koss Cliffs, Ernestinabury, Norway,45473 Zechariah Village, Muhammadtown, Ireland,4891 Hane Forges, Port Meta, Kazakhstan",
                            Released = 2023,
                            Synopsis = "Rerum impedit natus quos aut voluptatibus est modi. Dolorem reprehenderit quis nisi. Labore dignissimos et voluptate. Asperiores ea repudiandae eum nostrum perspiciatis. Assumenda eveniet esse dolor ut voluptates. Et numquam dolore facilis qui corrupti.",
                            Title = "Dedrick"
                        },
                        new
                        {
                            Id = 86,
                            Genre = "Electronic,Jazz,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "175 Vita Mountains, East Rasheed, Estonia,0056 Hudson Trail, West Leonieton, Nigeria,7980 Muller Gateway, Port Adriel, Albania",
                            Released = 2023,
                            Synopsis = "Eum placeat perspiciatis officia. Ea esse architecto et aut non. Laudantium voluptas repellat sunt voluptas recusandae quidem id.",
                            Title = "Vita"
                        },
                        new
                        {
                            Id = 87,
                            Genre = "Country,Non Music,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "19415 Drake Isle, Gottliebburgh, Finland,0448 Jazmyne Common, Lunamouth, Djibouti,0200 Drake Brook, South Kasandra, Grenada",
                            Released = 2022,
                            Synopsis = "Repudiandae eaque est exercitationem esse similique. Architecto sed adipisci quibusdam vel aut dignissimos et consequuntur. Aut ut labore. Eius culpa et et maiores velit.",
                            Title = "Monica"
                        },
                        new
                        {
                            Id = 88,
                            Genre = "Stage And Screen,Soul,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "7841 Danny Courts, Lockmantown, Guatemala,3041 Clovis Mill, Mabelshire, Guam,549 Fernando Causeway, Larkinland, Netherlands",
                            Released = 2022,
                            Synopsis = "Repudiandae cum reiciendis. Porro et occaecati velit laboriosam voluptatem maxime voluptate repellendus. Quaerat ipsum qui perferendis sit natus sit quaerat consectetur numquam. Accusamus aut ipsum ab quibusdam sequi corporis eius autem dignissimos.",
                            Title = "Lennie"
                        },
                        new
                        {
                            Id = 89,
                            Genre = "Hip Hop,Reggae,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "7940 Alysha Glens, Corwinmouth, Turkey,436 Gibson Ville, Lornamouth, Christmas Island,5838 Jones Drive, Adeleside, Israel",
                            Released = 2022,
                            Synopsis = "Voluptatem sed quam. Voluptatem numquam qui ut rerum eos fugiat aperiam quo. Minus sit odit porro quis et rerum a. Corrupti ea tempore quasi ut alias est esse perferendis voluptatibus. Sapiente cumque non quis eveniet. Recusandae quis ut cum deleniti natus neque.",
                            Title = "Katelin"
                        },
                        new
                        {
                            Id = 90,
                            Genre = "Electronic,Stage And Screen,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "71174 Luigi Corner, Theahaven, Finland,551 Liliana Square, Krisborough, Syrian Arab Republic,93227 Schroeder Forks, Olahaven, Switzerland",
                            Released = 2023,
                            Synopsis = "Id dolor ut temporibus quod rem. Sed explicabo quasi eaque quam voluptatem temporibus. Sit sit inventore repellat voluptatibus placeat voluptas incidunt veritatis eveniet. Rerum placeat rem quaerat omnis eaque. Provident autem qui sit.",
                            Title = "Arne"
                        },
                        new
                        {
                            Id = 91,
                            Genre = "Rap,Soul,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "45027 Taryn Fords, South Ronny, Colombia,2669 Richard Lights, West Jacintoport, Timor-Leste,2002 DuBuque Land, South Brannonport, Virgin Islands, British",
                            Released = 2023,
                            Synopsis = "Consequuntur pariatur asperiores ut. Enim distinctio consequatur et delectus pariatur impedit non labore. Quia fugit itaque quibusdam praesentium laudantium ut fugiat. Impedit possimus veniam sit dolorem laboriosam accusamus. Sint et et occaecati nisi dolorem sunt.",
                            Title = "Tara"
                        },
                        new
                        {
                            Id = 92,
                            Genre = "Metal,Rock,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "077 Nolan Grove, East Reginaldstad, Puerto Rico,52584 Andrew Trafficway, West Adellmouth, Uganda,773 Ernesto Course, North Mariela, Turkey",
                            Released = 2023,
                            Synopsis = "Qui dolores nobis saepe sint magni id. Quis consequuntur aliquid. Mollitia laudantium dolor laborum. Cumque repellat ipsum non. Eius est inventore dicta blanditiis quia ut corporis.",
                            Title = "Makenzie"
                        },
                        new
                        {
                            Id = 93,
                            Genre = "Reggae,Hip Hop,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "69920 Erdman Turnpike, New Samson, Bulgaria,45034 Vincenza Terrace, East Annalise, Equatorial Guinea,4387 Hahn Tunnel, West Bradyport, Grenada",
                            Released = 2023,
                            Synopsis = "Hic ut iure fugiat qui sit perferendis in. Rerum excepturi optio enim asperiores cum suscipit maxime natus. Voluptate aperiam tempora et. Eos enim asperiores omnis. Dolorum atque qui temporibus vero amet. Ullam itaque labore saepe possimus libero reiciendis.",
                            Title = "Frederic"
                        },
                        new
                        {
                            Id = 94,
                            Genre = "Funk,Jazz,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "64200 Breitenberg Vista, East Dock, Sao Tome and Principe,81317 Morar Circles, East Deronborough, Malta,2455 Jude Cliff, New Dorian, Reunion",
                            Released = 2023,
                            Synopsis = "Nisi et ab aut. Nisi non eaque voluptatibus consectetur. Qui corporis harum. Facilis corrupti reprehenderit voluptas beatae in fuga ea magni. Praesentium consequatur accusamus voluptates pariatur delectus est nihil expedita.",
                            Title = "Lelia"
                        },
                        new
                        {
                            Id = 95,
                            Genre = "Country,Classical,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "62076 Jessika Springs, West Anneton, Timor-Leste,351 Huel Manor, Rossland, Liechtenstein,63351 Sarai Row, Garretfurt, Serbia",
                            Released = 2023,
                            Synopsis = "Tempora dolorem qui. Voluptatum doloribus ut necessitatibus molestias vel sint dolorem eveniet doloribus. Dolorem doloremque iure aut quaerat velit et saepe.",
                            Title = "Asa"
                        },
                        new
                        {
                            Id = 96,
                            Genre = "Folk,World,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "289 Gibson Drive, Coltonmouth, Sao Tome and Principe,857 Bryana Knoll, Noahhaven, Moldova,2049 Kareem Cliff, Lake Billyville, Vanuatu",
                            Released = 2023,
                            Synopsis = "Quia perferendis autem earum dolore. Rerum aut repellendus velit. Est delectus ut vel optio voluptatem quis animi tempore porro. Est ut molestiae minima perspiciatis reiciendis et id ipsam quas. Nulla qui non minima quia ut itaque aut aperiam ipsam.",
                            Title = "Alivia"
                        },
                        new
                        {
                            Id = 97,
                            Genre = "Funk,Soul,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "5598 Zboncak Views, West Jarredborough, South Africa,29867 Wunsch Passage, New Damon, Saint Pierre and Miquelon,089 Junius Track, South Alvinaton, Lebanon",
                            Released = 2023,
                            Synopsis = "Saepe minima et consequatur dolor quasi. Consequuntur dolorum hic et. Quia officia dolor repellendus suscipit eum.",
                            Title = "Kayli"
                        },
                        new
                        {
                            Id = 98,
                            Genre = "Rap,Reggae,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "74905 Purdy Parkways, East Brisa, Pitcairn Islands,690 Beatty Coves, Port Chandlerberg, Macao,9450 Olin Isle, Kuphalstad, Saint Helena",
                            Released = 2023,
                            Synopsis = "Et laudantium recusandae nisi perferendis quisquam. Magni minus amet magnam molestias. Quo officia molestiae labore architecto non doloribus.",
                            Title = "Gilda"
                        },
                        new
                        {
                            Id = 99,
                            Genre = "Blues,Rock,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "5272 Hirthe Knolls, South Thad, Nicaragua,8363 Dicki Vista, Mohammadmouth, Sweden,8728 Renner Plaza, Framiburgh, French Guiana",
                            Released = 2023,
                            Synopsis = "Debitis tenetur voluptatem quasi voluptas dolores velit atque. Ut magni voluptas non architecto asperiores rerum possimus maiores. Debitis qui cumque autem. Error dolor aut id quia ea. Dolores dignissimos laboriosam assumenda sequi facere doloribus. Magni id omnis neque.",
                            Title = "Kyleigh"
                        },
                        new
                        {
                            Id = 100,
                            Genre = "World,Latin,Funk",
                            ImdbRating = 7.4f,
                            ImdbURL = "808 Renee Falls, Lakinborough, Nicaragua,523 Gutkowski Rapid, Percyborough, Suriname,795 Kira Drives, South Stephanialand, Maldives",
                            Released = 2023,
                            Synopsis = "In veniam et possimus incidunt occaecati voluptatem facere dignissimos. Est expedita sit aperiam autem recusandae eaque aspernatur. Similique occaecati ab qui ullam nam odio. Quis ut quidem dicta. Ex maxime voluptas consequuntur. Et nam mollitia.",
                            Title = "Marcelo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
