// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext");

                    b.Property<float>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<string>("ImdbURL")
                        .HasColumnType("longtext");

                    b.Property<int?>("Released")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 18, 13, 24, 1, 732, DateTimeKind.Local).AddTicks(4857),
                            Genre = "Blues,Soul,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "98711 Horace Drive, Yasmeenberg, Honduras,5828 Jacobi Center, East Carlosbury, Netherlands,889 Kendrick Ramp, Naderburgh, Kyrgyz Republic",
                            Released = 2022,
                            Synopsis = "Consectetur quia facilis perspiciatis dolore quos. Dolorum culpa distinctio esse quisquam eum sed illo tempore blanditiis. Quas et officia sunt non quidem dolor beatae.",
                            Title = "Kira",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 946, DateTimeKind.Utc).AddTicks(4131)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 10, 17, 6, 48, 659, DateTimeKind.Local).AddTicks(9212),
                            Genre = "Reggae,Funk,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "292 Destiney Cliffs, North Lourdes, Uganda,752 Marco Cove, Karlibury, Comoros,99280 Daniel Estates, Jeradberg, Bahrain",
                            Released = 2023,
                            Synopsis = "Et veniam culpa quasi quo. Molestiae ullam quos voluptas omnis occaecati iste sequi. Eum cum hic est tempore sapiente maxime veniam. Qui tenetur eos neque magnam qui consequatur optio repellat. Nihil sed vel dolor magnam sit consequuntur. Officiis in enim porro quaerat voluptatum.",
                            Title = "Antonia",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 947, DateTimeKind.Utc).AddTicks(5524)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 8, 8, 24, 42, 481, DateTimeKind.Local).AddTicks(6962),
                            Genre = "Blues,Classical,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "65817 Abshire Crest, North Celestinochester, French Guiana,981 Elroy Points, South Camila, Bolivia,36828 Maggie Burg, Dickinsonside, Sao Tome and Principe",
                            Released = 2023,
                            Synopsis = "Veritatis laudantium ratione placeat delectus repudiandae est quis sint placeat. Aut harum officiis dolor nobis et perspiciatis et debitis. Sequi velit sequi enim voluptas. Quia eum dolor debitis dolores aut ut fuga maiores.",
                            Title = "Breana",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 950, DateTimeKind.Utc).AddTicks(7251)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 7, 22, 47, 26, 970, DateTimeKind.Local).AddTicks(4831),
                            Genre = "Blues,Folk,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "629 Rolfson Cliffs, Port Trevaburgh, Saudi Arabia,640 Soledad Square, Kuhicside, New Zealand,57429 Pete Pines, North Declanfort, Oman",
                            Released = 2023,
                            Synopsis = "Tempora soluta earum sit et. Et cumque necessitatibus. Ipsum id consequuntur eaque ipsam dolor. Voluptas saepe qui voluptates dolor est explicabo quo excepturi dolor. Sed aut et quas.",
                            Title = "Graham",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 951, DateTimeKind.Utc).AddTicks(9757)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 2, 10, 16, 48, 75, DateTimeKind.Local).AddTicks(8196),
                            Genre = "Rock,Rock,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "9401 Reggie Road, Boyerville, Finland,37953 Carson Keys, Keelingville, South Georgia and the South Sandwich Islands,3312 Esther Brook, East Salvatore, Romania",
                            Released = 2023,
                            Synopsis = "Harum libero eum quae hic excepturi voluptatibus ad. Tempore ipsam omnis. Molestiae ad ut delectus. Doloremque in beatae. Est sed libero. Nihil similique delectus totam possimus modi.",
                            Title = "Sigurd",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 953, DateTimeKind.Utc).AddTicks(934)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 12, 8, 0, 46, 9, 337, DateTimeKind.Local).AddTicks(1535),
                            Genre = "Funk,Metal,Rock",
                            ImdbRating = 7.4f,
                            ImdbURL = "4421 Schumm Springs, Altenwerthberg, Montserrat,9999 Brock Coves, Aureliemouth, Macedonia,2363 Nathanial Keys, East Gustave, Zambia",
                            Released = 2022,
                            Synopsis = "Culpa in nisi enim dolores eius molestiae natus nihil sed. Vel magnam rem omnis. Quo vel inventore quaerat sequi perspiciatis et harum. Veniam ratione et quidem vel vel omnis. Ducimus fuga cum eos et voluptatem quae consequatur quo.",
                            Title = "Destin",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 954, DateTimeKind.Utc).AddTicks(1821)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 8, 30, 22, 20, 47, 687, DateTimeKind.Local).AddTicks(905),
                            Genre = "Stage And Screen,Reggae,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "53039 Welch Walk, Port Carolinefurt, Cape Verde,7651 Boehm Springs, South Mireille, China,171 Cassin Locks, Dooleyton, Solomon Islands",
                            Released = 2022,
                            Synopsis = "Voluptatum praesentium voluptatem quia modi ducimus. Possimus voluptas est voluptatem aut incidunt. Odio ut consequatur qui aliquam. Est error numquam modi repudiandae explicabo.",
                            Title = "Rhianna",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 955, DateTimeKind.Utc).AddTicks(2705)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 9, 16, 15, 41, 47, 653, DateTimeKind.Local).AddTicks(2362),
                            Genre = "Metal,World,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "945 Carroll Place, Herzogfort, Colombia,9948 Jaylan Knolls, East Savannaborough, Brunei Darussalam,75398 Rocky Lakes, West Randall, Nigeria",
                            Released = 2022,
                            Synopsis = "Voluptas accusantium quod deserunt iusto excepturi repudiandae. Ullam eum id. Dolorem perferendis illum ut est incidunt itaque et deserunt. Iste qui et quasi fugiat deserunt ut dolores.",
                            Title = "Gay",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 956, DateTimeKind.Utc).AddTicks(4630)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 10, 6, 4, 18, 383, DateTimeKind.Local).AddTicks(2840),
                            Genre = "Non Music,Funk,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "2708 Reichel Wall, Alanafort, China,7267 Isobel Ports, Schuppeland, Democratic People's Republic of Korea,204 Samanta Trace, East Hortense, Samoa",
                            Released = 2023,
                            Synopsis = "Iure laudantium itaque accusamus alias consequatur odio dolore. Similique nobis dolores iste aut cumque ab velit. Incidunt qui vitae placeat eum sed consequatur explicabo. Corrupti soluta eaque accusamus autem iste in sed.",
                            Title = "Marquis",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 957, DateTimeKind.Utc).AddTicks(6516)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 24, 7, 20, 59, 659, DateTimeKind.Local).AddTicks(4911),
                            Genre = "World,World,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "1523 Yost Path, Port Joshua, Sri Lanka,13204 Heaney Lights, South Dan, Syrian Arab Republic,234 Glen Club, North Jaden, Christmas Island",
                            Released = 2023,
                            Synopsis = "Impedit quia nam dolorum autem rerum modi. Ullam minus ex fuga cum. Quisquam nam reprehenderit. Ipsa distinctio velit.",
                            Title = "Stuart",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 959, DateTimeKind.Utc).AddTicks(1384)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 2, 1, 14, 46, 20, 757, DateTimeKind.Local).AddTicks(1580),
                            Genre = "Country,Blues,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "392 Bruen Ridges, Gloverfort, Monaco,2483 Michel Stream, Welchburgh, Gambia,89795 Wintheiser Pass, East Andreannefort, New Zealand",
                            Released = 2022,
                            Synopsis = "Ratione ipsum doloremque. Enim repellendus ipsam eos sequi sit nobis. Velit magnam ut.",
                            Title = "Roosevelt",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 961, DateTimeKind.Utc).AddTicks(2310)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 9, 17, 9, 33, 4, 872, DateTimeKind.Local).AddTicks(4109),
                            Genre = "Hip Hop,Hip Hop,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "91622 Brent Island, Burniceborough, Nicaragua,18134 Junior Junction, Shannybury, Aruba,54611 Giovanni Corner, Rosalindfurt, Montenegro",
                            Released = 2023,
                            Synopsis = "Quo asperiores adipisci dolorem at enim deserunt laudantium pariatur. Veniam perferendis at nesciunt sed voluptas et at. Eaque et sapiente iste.",
                            Title = "Ottis",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 962, DateTimeKind.Utc).AddTicks(3587)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 8, 23, 5, 22, 39, 794, DateTimeKind.Local).AddTicks(8598),
                            Genre = "Funk,Folk,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "487 Paucek Square, East Orville, Falkland Islands (Malvinas),2584 Marks Islands, Pricebury, Burkina Faso,2888 Providenci Prairie, Lake Sasha, Bouvet Island (Bouvetoya)",
                            Released = 2023,
                            Synopsis = "Aliquam in atque harum deleniti quod quidem voluptatibus debitis. Odio soluta assumenda in sapiente natus deleniti. Asperiores qui sunt et aut culpa deleniti quod. Rerum aliquam officiis ut. Alias enim molestiae ut labore est aliquid. Iste enim cumque rerum perspiciatis amet sunt.",
                            Title = "Jessy",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 963, DateTimeKind.Utc).AddTicks(4682)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 3, 17, 9, 49, 14, 276, DateTimeKind.Local).AddTicks(8272),
                            Genre = "Non Music,Jazz,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "33213 Krajcik Hills, Schulisttown, Sudan,156 Mia Passage, Rauville, Tunisia,92348 Willy Harbors, Kaylimouth, Georgia",
                            Released = 2022,
                            Synopsis = "Vel deleniti incidunt est sit nihil odio animi qui ex. Asperiores quam doloribus ut accusantium repellat. Velit labore maiores et fugiat inventore qui sed qui sed. Nemo quasi nesciunt eum fugiat distinctio itaque ex.",
                            Title = "Cordie",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 964, DateTimeKind.Utc).AddTicks(5594)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 2, 3, 21, 25, 43, 823, DateTimeKind.Local).AddTicks(2125),
                            Genre = "World,Electronic,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "438 Green Ridge, South King, Pitcairn Islands,12647 Schowalter Center, Boscotown, Isle of Man,058 West Ridge, North Salvatorechester, Saint Barthelemy",
                            Released = 2023,
                            Synopsis = "Magni et qui veniam sed. Architecto aut corporis velit dolorem est. Hic ut quidem. Nesciunt repudiandae eaque rerum dolor non facilis laborum. Dicta ab consequatur inventore et.",
                            Title = "Caleb",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 965, DateTimeKind.Utc).AddTicks(7856)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 11, 8, 1, 49, 22, 633, DateTimeKind.Local).AddTicks(8885),
                            Genre = "Classical,Classical,Blues",
                            ImdbRating = 7.4f,
                            ImdbURL = "8231 Collier Crossing, Jerdeberg, Uganda,30178 Dooley Springs, Heidenreichburgh, Spain,37084 Jade Rapid, Swiftville, Reunion",
                            Released = 2023,
                            Synopsis = "In dolores iure tempora. Fugit placeat eos atque a rem ut expedita officiis ex. Vitae dolore reprehenderit quis dolorem ipsum et laborum quia qui.",
                            Title = "Trevion",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 966, DateTimeKind.Utc).AddTicks(9252)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 10, 8, 12, 56, 21, 873, DateTimeKind.Local).AddTicks(7259),
                            Genre = "Rock,Folk,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "7596 Frami Mountains, North Felipe, Mexico,649 Dayana Rapids, Kertzmannville, Nepal,743 Leo Course, Mitchellside, United Kingdom",
                            Released = 2022,
                            Synopsis = "Fuga veniam atque ut non non in modi consequatur. Veritatis distinctio unde alias nihil at quia quisquam placeat. In sunt soluta omnis dolorem dolorem cumque. Deleniti et nihil. Perferendis explicabo natus dolor. Quod mollitia voluptatem magni rerum qui.",
                            Title = "Kellie",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 968, DateTimeKind.Utc).AddTicks(302)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 9, 9, 13, 13, 9, 370, DateTimeKind.Local).AddTicks(6502),
                            Genre = "Reggae,Soul,Classical",
                            ImdbRating = 7.4f,
                            ImdbURL = "953 Mateo Dale, Lake Garretthaven, Kuwait,434 Tom Road, East Rodger, Hungary,06132 Krajcik Pike, East Shemar, Paraguay",
                            Released = 2023,
                            Synopsis = "Quaerat et dolor natus beatae aut voluptas qui rerum. Nulla eaque repellat ducimus quae nam laboriosam. Facilis dicta ipsa et. Et illum aliquam nulla ea. Vel et atque mollitia asperiores nihil.",
                            Title = "Granville",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 969, DateTimeKind.Utc).AddTicks(4345)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 5, 20, 0, 24, 19, 788, DateTimeKind.Local).AddTicks(2370),
                            Genre = "Jazz,Reggae,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "749 Padberg Canyon, North Neva, Israel,74282 Denesik Manor, Huelsmouth, Ireland,32736 Edison Rest, Lake Maddison, Pitcairn Islands",
                            Released = 2023,
                            Synopsis = "Molestiae nam quia totam. Earum perferendis velit. Alias sequi quis. Ipsa nobis non enim accusamus modi quisquam at aspernatur.",
                            Title = "Cristina",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 972, DateTimeKind.Utc).AddTicks(2281)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 4, 11, 13, 13, 17, 210, DateTimeKind.Local).AddTicks(8140),
                            Genre = "Latin,Hip Hop,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "0089 Kemmer Island, New Tiara, Reunion,55335 Runolfsdottir Ville, Bodeton, Aruba,83175 Kertzmann Estates, North Addisonmouth, Greece",
                            Released = 2023,
                            Synopsis = "Error nulla fugiat ut error illo voluptate voluptatibus. Dicta sequi et corrupti at exercitationem non. Quos nam minima. Ut molestias beatae ea.",
                            Title = "Emmie",
                            UpdatedAt = new DateTime(2023, 10, 2, 13, 35, 59, 973, DateTimeKind.Utc).AddTicks(4127)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
