// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext");

                    b.Property<float>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<string>("ImdbURL")
                        .HasColumnType("longtext");

                    b.Property<int?>("Released")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Country,Metal,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "861 Alexandria Springs, West Velvafort, Somalia,594 Raynor Meadow, Beckerside, Burundi,93901 Kayli Bridge, Nevastad, Christmas Island",
                            Released = 2022,
                            Synopsis = "Est quae libero labore eligendi. Nisi facere magnam ut dicta deleniti non. Aut harum eaque temporibus. Voluptatem non id. Numquam ut dolores provident.",
                            Title = "Rene"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Pop,Electronic,Metal",
                            ImdbRating = 7.4f,
                            ImdbURL = "41790 Langosh Alley, Labadieport, Peru,580 Helene Spurs, South Cordia, Rwanda,1695 Gilbert Fort, North Danielle, Pitcairn Islands",
                            Released = 2023,
                            Synopsis = "Molestiae aliquam dolores maxime exercitationem hic esse. Voluptates quaerat at aperiam saepe harum ea. Perferendis esse quo amet quasi quia.",
                            Title = "General"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Folk,Stage And Screen,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "6005 Clare Lodge, Lake Jonathon, Czech Republic,165 Luettgen Garden, Bartholomeshire, Libyan Arab Jamahiriya,840 Hubert Ways, Herminafurt, Bahrain",
                            Released = 2023,
                            Synopsis = "Amet sunt voluptas. Architecto dolorem voluptatem. Doloremque voluptatem quod distinctio et culpa enim minima minus omnis. Iure commodi et omnis excepturi ducimus dolorem laudantium velit. Alias et qui fuga iste aliquid qui est voluptatem nihil.",
                            Title = "Darryl"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Rock,Rock,Hip Hop",
                            ImdbRating = 7.4f,
                            ImdbURL = "0432 Oceane Skyway, New Hellen, United States Minor Outlying Islands,3551 Hackett Harbors, Terrencestad, Niue,58825 Satterfield Mission, West Romaine, Bosnia and Herzegovina",
                            Released = 2022,
                            Synopsis = "Minus nostrum sit sequi in dolorem repellat in. Sequi et eum vero et sit impedit ut. Autem saepe modi facilis dolore.",
                            Title = "Tracy"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Folk,Metal,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "47827 Koepp Squares, Fayside, Reunion,2726 Berneice Stravenue, Schillerside, Guam,682 Botsford Views, Wolfhaven, Saint Kitts and Nevis",
                            Released = 2022,
                            Synopsis = "Voluptatem quasi ducimus vel. Blanditiis nihil repudiandae ut harum qui exercitationem consectetur. Impedit ducimus natus omnis dignissimos possimus. Est enim ut repellendus nemo veniam at praesentium aspernatur occaecati. Debitis tempore ullam nesciunt sunt in molestiae autem quo. Deleniti eveniet omnis deleniti ut hic neque sed quo rerum.",
                            Title = "Antonietta"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Country,Country,Folk",
                            ImdbRating = 7.4f,
                            ImdbURL = "263 Lemke Extension, West Corafort, Panama,707 Ludwig Corners, West Magdalena, Monaco,2031 Kiana Street, North Myriamtown, Reunion",
                            Released = 2023,
                            Synopsis = "Vel et qui ex inventore dolore debitis. Tempora dolore dolorem corrupti. Voluptate id iure voluptas velit similique laboriosam officia sint autem. Consequatur doloribus culpa quasi suscipit rerum sequi in molestiae.",
                            Title = "Johann"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Country,Non Music,Pop",
                            ImdbRating = 7.4f,
                            ImdbURL = "05727 Adonis Knoll, New Ashleigh, Brazil,869 Nienow Trail, Rashawntown, Mexico,64747 Wayne Rue, Keelington, Djibouti",
                            Released = 2023,
                            Synopsis = "Ullam sint quisquam adipisci quod voluptates. Ullam voluptas deserunt facere quasi. Quia enim et harum adipisci nulla. Rerum voluptatum in ut nostrum eum ut atque fugit cum. Fugit totam in quaerat asperiores ipsa.",
                            Title = "Brooklyn"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Electronic,Latin,Country",
                            ImdbRating = 7.4f,
                            ImdbURL = "5044 Aliza Roads, South Rettastad, Montserrat,7643 Lockman Highway, Lake Bartonside, Bolivia,419 Tia Mews, South Rosemariehaven, Georgia",
                            Released = 2023,
                            Synopsis = "Laborum vel rerum qui et aperiam at autem aliquid. Quia velit modi officiis ratione fuga iure. Natus recusandae aut architecto dolor quibusdam delectus quia quasi. Enim saepe voluptatem expedita.",
                            Title = "Kylie"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Latin,Metal,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "220 McGlynn Tunnel, Shawnborough, Niue,2469 Gleason Square, Lake Vergiechester, Niger,007 Dickinson Bypass, Tarynside, Bahamas",
                            Released = 2022,
                            Synopsis = "Quo perspiciatis sapiente beatae ut minus corporis quisquam non. Possimus ipsa et ad consequatur tempora. Iusto iste voluptates vel sit voluptatem quasi. Distinctio non dolorum nostrum similique dignissimos veniam rerum officia. Dolorum qui soluta illum sit cumque velit.",
                            Title = "Rogers"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Hip Hop,Funk,Latin",
                            ImdbRating = 7.4f,
                            ImdbURL = "07484 Lucinda Lodge, West Alexie, Tunisia,52821 Bednar Points, Lake Rosahaven, Niger,760 Halvorson Mission, Jenkinsland, Virgin Islands, British",
                            Released = 2022,
                            Synopsis = "Et ipsa eum sapiente occaecati. Aut sit accusamus. Illo accusamus sint veritatis. Autem illo laudantium animi adipisci rerum nulla qui. Quis rem et quis. Qui atque et et in.",
                            Title = "Zella"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "World,Blues,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "893 Nedra Square, Auerburgh, Latvia,78446 Hills Junctions, Hoppeshire, Cayman Islands,3024 Lorine Summit, Vivienside, Chile",
                            Released = 2023,
                            Synopsis = "Est velit eos perferendis eum sit debitis magni. Laudantium ipsum labore doloremque eaque iste blanditiis consectetur est asperiores. Quis in porro. Deserunt aliquam dolores fugiat. Ea quidem sapiente ut in voluptas consequuntur blanditiis voluptatem. Qui nam hic non dolores consequatur enim esse rem.",
                            Title = "Jean"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Pop,Reggae,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "02818 Lehner Junctions, Daughertyberg, Cyprus,40628 Schulist Fords, Jarvisburgh, Brazil,16421 Enos Course, Lake Kearabury, Tanzania",
                            Released = 2023,
                            Synopsis = "Neque vel ipsa et fugit qui tenetur amet est. Error perspiciatis quia dolor ut nobis quaerat voluptatem animi est. Adipisci ea porro voluptas. Similique non eum voluptas eligendi aut quam deleniti.",
                            Title = "Sigurd"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Reggae,Hip Hop,Rap",
                            ImdbRating = 7.4f,
                            ImdbURL = "077 Devyn Prairie, Port Arthur, Finland,176 Anahi Club, South Branson, Peru,1055 Sporer Fords, Tremblayhaven, Bangladesh",
                            Released = 2022,
                            Synopsis = "Iusto voluptate et saepe dolorum quia reiciendis non optio eum. Incidunt mollitia inventore aliquid architecto ut voluptas molestiae enim qui. Voluptatum ea occaecati laborum quaerat natus id cupiditate eos at. Quo nesciunt asperiores molestiae in animi aliquid vel ut quibusdam. Optio tempora aperiam incidunt qui consequuntur dolore. Ipsa culpa ipsam eius illum ut illo consequuntur.",
                            Title = "Alek"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Country,Metal,Jazz",
                            ImdbRating = 7.4f,
                            ImdbURL = "116 Kadin Isle, Spinkaville, Belize,668 Corkery Village, Brakusside, Algeria,4295 Klein Ways, Kovacekton, Honduras",
                            Released = 2023,
                            Synopsis = "Eveniet id sint. Aut aperiam magni excepturi consectetur odio. Sint enim officia blanditiis. Odio vitae iusto aliquam praesentium ad rerum. Ducimus architecto ratione iste.",
                            Title = "Darrel"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Folk,Pop,World",
                            ImdbRating = 7.4f,
                            ImdbURL = "2143 Clarabelle Plains, West Simeonfort, Sweden,3451 Morgan Skyway, Shannaton, Nicaragua,0788 Kohler Field, Beerview, Republic of Korea",
                            Released = 2023,
                            Synopsis = "Possimus et et ea repellendus repudiandae consequuntur. Cumque et maxime vel ut autem blanditiis dolorem voluptates. Quo accusamus quia deserunt odit excepturi. Ipsum dignissimos quod aut.",
                            Title = "Brigitte"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Non Music,Electronic,Non Music",
                            ImdbRating = 7.4f,
                            ImdbURL = "3924 Dickinson Plaza, Lake Eudora, Tunisia,5711 Renner Knolls, Lake Danikastad, Singapore,2468 Gottlieb Forges, Krajcikport, Republic of Korea",
                            Released = 2023,
                            Synopsis = "Ducimus omnis aspernatur. Provident corrupti aut nesciunt vitae sed nobis expedita ut. Molestiae et ratione. Ea cum repellat totam est placeat at non.",
                            Title = "Wayne"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Funk,Jazz,Reggae",
                            ImdbRating = 7.4f,
                            ImdbURL = "069 Jody Vista, Heathview, Mali,79500 Adams Curve, Keithview, Svalbard & Jan Mayen Islands,624 Harry River, West Audrey, China",
                            Released = 2022,
                            Synopsis = "Dolorum dicta saepe tempora. Beatae enim quaerat molestias. Odio provident voluptatum. Ex quod deleniti ipsa vitae et eos quia. In assumenda nobis nisi qui autem. Iure vitae quos animi quasi explicabo labore aut debitis labore.",
                            Title = "Henry"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Country,Jazz,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "85691 Stiedemann Neck, Amiefurt, Namibia,183 Christ Knoll, North Jammiefurt, Saint Vincent and the Grenadines,59604 Nichole Ferry, Hellerborough, Antarctica (the territory South of 60 deg S)",
                            Released = 2022,
                            Synopsis = "Quo adipisci assumenda itaque reprehenderit. Corrupti quis rerum. Autem quasi consequatur voluptas qui et asperiores non. Voluptatum consequatur magni ut accusamus beatae.",
                            Title = "Micah"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Non Music,Electronic,Stage And Screen",
                            ImdbRating = 7.4f,
                            ImdbURL = "902 Hosea Manor, Stiedemannchester, Wallis and Futuna,38216 Wuckert Fork, East Evie, Palau,18213 Dedric Harbors, Lake Geoffreyfort, San Marino",
                            Released = 2023,
                            Synopsis = "Eos impedit rem id mollitia dignissimos est excepturi deserunt. Alias et sunt blanditiis corporis. Repellat sed quia dolorum et voluptatum et. Autem rerum atque quia delectus beatae. Sunt et tempora earum iusto et optio rerum minus. Suscipit fugiat placeat odio qui.",
                            Title = "Cletus"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Blues,Stage And Screen,Soul",
                            ImdbRating = 7.4f,
                            ImdbURL = "1628 Haag Vista, Lake Isabella, United States of America,678 King Parkway, Vandervortchester, Spain,0971 Hegmann Union, Blancatown, Cayman Islands",
                            Released = 2022,
                            Synopsis = "Est laborum nihil praesentium nesciunt iste consectetur iusto. Odio ut sint velit beatae qui. Sint quia totam et in.",
                            Title = "Myrtice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
